### ISSUE TITLE
Office 365 Calendar Integration

### ISSUE THREAD

**Issue by emrysal** [calendso/calendso#10]

**Comment by thekeviv** [comment]
@baileypumfleet Is anyone working on this? If not, I am interested in contributing this feature. I have worked with the Office 365 graph API in C#. I am expecting some similarities in their JS SDK as well. If no one is working on this, can you please assign it to me?

**Comment by mattmattox** [comment]
I second this, having Office 365 Calendar Integration is a must because so many businesses use Office365.

**Comment by baileypumfleet** [comment]
I absolutely agree. Microsoft 365 will be the next integration we produce, because of it's substantial market share.

**Comment by baileypumfleet** [comment]
@thekeviv I'll assign this to you. We also have a guy in the Slack who is interested in working on this, so if you join the Slack you may be able to work with him on this.

**Comment by thekeviv** [comment]
I pinged the 2 people mentioned in the o365 conversation on Slack. Will try to onboard myself with the code and start work on this over the next few days. Will try to add updates as I make progress on this. Thanks!

**Comment by fachcraftim** [comment]
I'm also interested in this.
@thekeviv let me know if there is anything I can support you with, if you are going to publish your branch let me know

**Comment by thekeviv** [comment]
Hi @fachcraftim , I haven't had time to look into it yet (and will not for at least a few days). In the interest of time, feel free to start work on it in your branch and we can collaborate later.

**Comment by thekeviv** [comment]
Unassigned myself as this issue is being worked by others. Please check development channel in slack for more info

**Comment by emrysal** [comment]
The documentation is pending; but I've opened pull request #87

**Comment by baileypumfleet** [comment]
PR has been merged, so I'll close this one off. Thanks guys :)
