### ISSUE TITLE
Registration upon user invite through Teams is broken

### ISSUE THREAD

**Issue by emrysal** [calendso/calendso#1015]
### Issue Summary

When someone is invited to join a team, the join link redirects to settings instead of sign up, as a new user of the team am not able to signup.

### Steps to Reproduce

1. Invite someone to a team.
2. On getting redirected to sign up page, fill in form.
3. Press "Sign up"
3. It says user already registered.

![image](https://user-images.githubusercontent.com/1046695/138117435-0da54c67-57f9-4857-b62c-8896b4093ab8.png)

**Comment by zomars** [comment]
It may come from here: https://github.com/calendso/calendso/blob/a6eed6ffccf9ef7f51509a5068c23e72869b2056/lib/emails/invitation.ts#L51-L54
