### ISSUE TITLE
Cal Sans don't support espacial characters for example Á

### ISSUE THREAD

**Issue by angel8au** [calendso/calendso#1020]
Found a bug? Please fill out the sections below. 👍

Leters with acents like Á á É é ó Ó ú  for spanish user do not work.

<img width="1032" alt="Captura de Pantalla 2021-10-20 a la(s) 8 35 47 p m" src="https://user-images.githubusercontent.com/37971517/138202043-10fc2de3-38fa-4afc-be44-72c9497e0b8a.png">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: Firefox
- Spanish characters.

**Comment by PeerRich** [comment]
forwarded this to the creator of Cal Sans :)

**Comment by PeerRich** [comment]
![image](https://user-images.githubusercontent.com/8019099/139561430-c9d1a817-abab-4b6d-a1db-4677da646052.png)

fixed https://github.com/calendso/calendso/pull/1087
