### ISSUE TITLE
Multiple users per event type?

### ISSUE THREAD

**Issue by Tang8330** [calendso/calendso#104]
Looking at the [docs](https://api.docs.calendso.com/docs/calendso/calendso.yaml/paths/~1api~1availability~1:user/get) and issues - it's not clear that we can have multiple users under the same event type.

Example:
* Event Type: Book a sales call
* Users: Members of the sales team

When fetching availability for the event type, it would check individual members calendars

**Comment by chrispruitt** [comment]
Is this on the roadmap at all? I see that there is a "Teams" section in the Settings area, but after creating a team and adding members it doesn't seem to do anything. Am I missing the point of "Teams" are teams simply the foundation for this feature?

**Comment by PeerRich** [comment]
correct, teams are the foundation of this feature

**Comment by DanielWeeber** [comment]
Is this possible now? This would be THE feature to switch from calendly.

**Comment by ConnorGargano** [comment]
Hi @DanielWeeber

Our engineering team are currently working on this and we hope to be releasing this very soon!
I will provide you with an update as soon as one becomes available 🙌

**Comment by baileypumfleet** [comment]
Hi all,

This was released a few weeks ago.  We now have collective and round robin event types.

**Comment by jimafisk** [comment]
In case someone else is confused how this works, before you create a team you can only add one event type (https://app.cal.com/event-types) that will look something like this:

<details>
<summary>Single Event Type Screenshot</summary>

![event_type](https://user-images.githubusercontent.com/5913244/140260621-325c2a41-28ad-487b-8c45-adcb1cf5c830.png)

</details>

As soon as you add a new Team in your settings (https://app.cal.com/settings/teams), you can create new event types under a team:

<details>
<summary>Team Event Types Screenshot</summary>

![team](https://user-images.githubusercontent.com/5913244/140260929-53acae88-cdbf-4f8a-af7e-2ca98d31837d.png)

</details>

When creating the new event type you will have "Scheduling Type" options for Collective or Round Robin.
