### ISSUE TITLE
[BUG] Deploy on Railway button gives a 500 error

### ISSUE THREAD

**Issue by marcorichetta** [calendso/calendso#1052]
### Issue Summary

The button to deploy to Railway gives a 500 error on a serverless function execution on Vercel.
This may be an error on Railway. I created the issue to warn you.

### Steps to Reproduce

1. Click the "Deploy on Railway" button on the [readme](https://github.com/calendso/calendso#railway) or use directly the link https://railway.app/new/template?template=https%3A%2F%2Fgithub.com%2Fcalendso%2Fcalendso&plugins=postgresql&envs=GOOGLE_API_CREDENTIALS%2CBASE_URL%2CNEXTAUTH_URL%2CPORT&BASE_URLDefault=http%3A%2F%2Flocalhost%3A3000&NEXTAUTH_URLDefault=http%3A%2F%2Flocalhost%3A3000&PORTDefault=3000
2. 
![imagen](https://user-images.githubusercontent.com/19599150/138968547-b58f005d-72a8-4b7a-9916-bc2a190e88f9.png)

**Comment by marcorichetta** [comment]
@ConnorGargano Today I retried and could deploy the app successfully! :+1:

**Comment by ConnorGargano** [comment]
Brilliant!
