### ISSUE TITLE
Issue with Busy Times

### ISSUE THREAD

**Issue by jtylerhartley** [calendso/calendso#107]
A couple things I noticed on the booking page. I am able to book times on Calendso that interfere with other events. For example, if I am free at 12:30pm and try to book at 30 min meeting it allows me to because 12:30pm is "free", but it does not look ahead to see if I have a conflict from the time period from 12:31-1:00pm. I have an event starting at 12:50pm unfortunately :(

**Comment by baileypumfleet** [comment]
Does this PR fix things for you? #180

**Comment by jtylerhartley** [comment]
> Does this PR fix things for you? #180

Yes, closing it now. @baileypumfleet
