### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by ile** [calendso/calendso#114]
Demo gives "500 Internal Server Error.": https://calendso.com/rick/6

![image](https://user-images.githubusercontent.com/433707/116417745-3d065600-a844-11eb-9c22-c8fe1f1fdee7.png)

**Comment by baileypumfleet** [comment]
Thanks for reporting this, it's now been fixed. A recent change in the URL structure caused this. For any future bugs related to our website, please email support@calendso.com, as the website is not covered under this repository.

**Comment by ile** [comment]
Thank you. Let me just continue here, that when you "Cancel" here:

![image](https://user-images.githubusercontent.com/433707/116420414-9ff8ec80-a846-11eb-85e9-48f651e2ccb7.png)

.. You get this:

![image](https://user-images.githubusercontent.com/433707/116420471-aa1aeb00-a846-11eb-99c5-c2eb64302700.png)

Probably an url thing.
