### ISSUE TITLE
Zoom link missing from calendar invite

### ISSUE THREAD

**Issue by hamstah** [calendso/calendso#1146]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

- starting a few days ago, calendar invites don't include zoom links anymore
- the meetings are created in zoom but no mention of it in the invite
- zoom is still connected
-
### Steps to Reproduce

??

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

Browser is chrome 95 but don't think it's relevant.

**Comment by drwb** [comment]
Same issue here.

Built with docker. Integration with Zoom successful via (https://docs.cal.com/docs/integrations/zoom). 

Zoom meeting *is* present in confirmation emails on event creation, but is missing from the invite. Invite says "integrations:zoom".

**Comment by hamstah** [comment]
Also I noticed that when a meeting is cancelled the zoom call is not.

**Comment by ConnorGargano** [comment]
Hi @hamstah,
We are currently working on a fix for this and it should be resolved soon.
