### ISSUE TITLE
Reverse proxy instructions

### ISSUE THREAD

**Issue by pat-s** [calendso/calendso#116]
- NGINX
- Apache

Templates for running in `/` and in sub directories, e.g. `$DOMAIN/calendso`.

**Comment by baileypumfleet** [comment]
Will not be adding this, as environment setup is the user's responsibility, not this project's.

**Comment by pat-s** [comment]
This was not a request to you directly but that it would be nice to have.

Adding such instructions to the README would certainly be helpful and get more people on board which need to get this working behind a reverse proxy.

> Will not be adding this, as environment setup is the user's responsibility, not this project's.

With this arguments, there should also be no need for docker instructions then as this would also relate to "environment setup". 

Maybe this decision can be re-evaluated.

**Comment by SimonBiggs** [comment]
For others finding this via Google, I have been having success with the following nginx config:

https://github.com/assistancechat/assistance/blob/45484bf6792cf5aec6b8ba7354d79f0e23da5fd9/dev/server/nginx-site.conf#L149-L167
