### ISSUE TITLE
Can not accept licence

### ISSUE THREAD

**Issue by drwb** [calendso/calendso#1160]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Licence acceptance banner remains even after adding lines to .env 

Have tried =‘ agree’ = agree =“ agree”

### Technical details
Cal docker with manual fix #41 implemented.

**Comment by drwb** [comment]
Sorry, yes, it was "agree" not accept. Neither work though.
<img width="995" alt="Screenshot 2021-11-11 at 12 39 50" src="https://user-images.githubusercontent.com/16479230/141299664-4762c27d-3b2d-4beb-971f-2fcdd768e55e.png">
<img width="603" alt="Screenshot 2021-11-11 at 12 37 57" src="https://user-images.githubusercontent.com/16479230/141299669-1f20c3de-9274-4a4d-ae4c-1539bb84cd03.png">

**Comment by PeerRich** [comment]
I believe there was a problem with docker environments not being picked up.

just remove it from Shell.tsx:
![image](https://user-images.githubusercontent.com/8019099/141532927-505d2aa8-146d-47ab-ba3c-90035b5c7003.png)

**Comment by wivaku** [comment]
https://github.com/calendso/docker/issues/43

**Comment by BahrouniYousra** [comment]
Have you solved the problem ? I have the same here

**Comment by drwb** [comment]
I edited out the banner in the template as recommended above.

**Comment by bigbaldy1128** [comment]
BASE_URL has the same problem in docker

**Comment by PeerRich** [comment]
we're currently debugging why docker is not picking up all variables correctly. maybe @bvallelunga can help

**Comment by TheBestMoshe** [comment]
Variables that begin with `NEXT_PUBLIC` are only used at build time. The values are embedded in the build output.

See [this disucssion](https://github.com/vercel/next.js/discussions/17641#discussioncomment-339555) for a possible workaround.

**Comment by PeerRich** [comment]
https://github.com/vercel/next.js/discussions/17641#discussioncomment-339555

**Comment by zeluspudding** [comment]
Should be reopened as inability to set  `NEXT_PUBLIC_LICENSE_CONSENT` and `BASE_URL` via env variables are still an issue on Heroku's one click deploys.
