### ISSUE TITLE
"integrations:zoom" (not an invite link) in location in calendar invite

### ISSUE THREAD

**Issue by drwb** [calendso/calendso#1169]
A summary of the issue. This needs to be a clear detailed-rich summary.
If Location is set to Zoom in the Event Type, when an event is booked the confirmation emails contain the _correct_ Zoom details, but the calendar invite Location contains _integrations:zoom_.

<img width="418" alt="Screenshot 2021-11-11 at 13 11 12" src="https://user-images.githubusercontent.com/16479230/141304006-928c369c-7379-49c0-9a18-27b8c0ff0677.png">
<img width="479" alt="Screenshot 2021-11-11 at 13 10 24" src="https://user-images.githubusercontent.com/16479230/141304010-602fcbb2-47b7-4485-8d2b-5676057b8f71.png">
<img width="480" alt="Screenshot 2021-11-11 at 13 09 04" src="https://user-images.githubusercontent.com/16479230/141304012-440ce8c4-b850-4dd8-9b86-bbb58dba413f.png">

Docker deployment with manual change in https://github.com/calendso/docker/pull/41/commits/77ffd4d7858352289678428802544dc82ecbbb7e.

Zoom integration otherwise works fine. Google Calendar integration otherwise works fine.

**Comment by rberrelleza** [comment]
This happens on 100% of my meetings. I'm using cal.com

**Comment by ConnorGargano** [comment]
Hi there,
We are aware of this and someone is currently working on a resolution.

**Comment by drwb** [comment]
If it's closed, can you link to the PR please?

**Comment by ConnorGargano** [comment]
Hi there,

I have closed this issue as it's already currently raised under another here:

https://github.com/calendso/calendso/issues/1091

This is regarding Zoom as-well as Daily integrations
