### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by baileypumfleet** [calendso/calendso#117]
Add email notifications when an event is booked.

**Comment by herdani** [comment]
That's one I'm waiting for to start using it! 👍

**Comment by baileypumfleet** [comment]
I forgot, but this was done ages ago

**Comment by pensierinmusica** [comment]
@zomars @PeerRich @emrysal @hariombalhara @sean-brydon @Udit-takkar @alannnc @alishaz-polymath can you please make these email notifications optional, through some toggle button in settings?

We're getting our inbox spammed with all these messages and there doesn't seem to be a way to turn it off. I know we could create a filter in our email client, but like in every similar scheduling platform, this option should exist. It'd be great if you could implement it asap and even write something here about the timeline.

Thanks in advance for your kind consideration!
