### ISSUE TITLE
Changing ROOT URL / `/auth` location

### ISSUE THREAD

**Issue by pat-s** [calendso/calendso#118]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I would like to run `calendso` in a subdirectory.
While redirection works for the initial request, the `/auth` location seems to be hardcoded.
Hence all requests from within calendso are requesting `$DOMAIN/auth` instead of `$DOMAIN/calendso/auth`.

I would be ok with using `$DOMAIN/auth` but in my case I have another service already running at `$DOMAIN/auth`, hence I think there is a need for a dynamic ROOT URL variable within project.

**Comment by emrysal** [comment]
Hi @pat-s 

Adding `NEXTAUTH_URL=$DOMAIN/calendso/` (or `NEXTAUTH_URL=$DOMAIN/calendso/api/auth`) may fix your issue.

**Comment by pat-s** [comment]
Thanks! Looked promising but did not help.

Maybe because the default of the env var points to a localhost port and cannot accept a public URL therefore?

**Comment by baileypumfleet** [comment]
Is running Calendso on a subdomain possible?

**Comment by emrysal** [comment]
Hi @pat-s 

Went a little deeper into the issue for you and I found https://github.com/nextauthjs/next-auth/issues/499 with helpful suggestions; 

Most relevant to your situation is https://github.com/nextauthjs/next-auth/issues/499#issuecomment-701050088

(P.s. no, public URLs work fine)

**Comment by pat-s** [comment]
Thanks @emrysal, looks promising.
I tried setting `NEXT_PUBLIC_NEXTAUTH_URL` but without success unfortunately.

I am not into JS myself but it might be that additional changes in the code are required so that `NEXT_PUBLIC_NEXTAUTH_URL` is picked up?

Happy to test proposed solutions or to apply simple changes to the code.

> Is running Calendso on a subdomain possible?

I have not tried yet because this would mean spinning up a new machine just for this service.
We would like to host it on a machine with many existing services (in a subpath).

**Comment by baileypumfleet** [comment]
Changing the environment variable to prepend the `NEXT_PUBLIC` simply just exposes that environment variable to the client, and so it wouldn’t require a change in code. Furthermore, you are able to run Calendso on a subdomain using a machine with other existing services. Just use virtual hosts or soemthing, it’s super simple.

**Comment by pat-s** [comment]
> Changing the environment variable to prepend the NEXT_PUBLIC simply just exposes that environment variable to the client, and so it wouldn’t require a change in code.

Sure. The question was if it has an effect then / if the code is actually making use of the env var then.
I am not into JS and would like to avoid browsing source code of an unknown language if there are people with more knowledge around :)

< Furthermore, you are able to run Calendso on a subdomain using a machine with other existing services. Just use virtual hosts or soemthing, it’s super simple.

Thanks, I am aware of this possibility - working in the devops space :)
However, I would like to keep things together and concise and run it on a machine in a subpath where `/auth` is already occupied.
It would be great if this could be supported/documented by the project.
I am certainly not the only person with a need for such a configuration but I assume you might argue similar as in #116. 

Thanks for your help.

**Comment by baileypumfleet** [comment]
Yes, the code would be making use of the environment variable still, that shouldn’t be the issue. If nothing in the issue Alex mentioned earlier on Next-Auth’s repo doesn’t work, we may have to put this on hold for a while, as we don’t have the resources at the moment to be able to support lots of custom configurations, and therefore only support installations on their own domain/sub domain. Hopefully we can look at this further in the future
