### ISSUE TITLE
Release v1.1 fails to build

### ISSUE THREAD

**Issue by jstrellner** [calendso/calendso#1184]
### Issue Summary

Fails to build on self-hosted install (on Railway)

### Steps to Reproduce

1. From a previously working local repo, I ran: `git pull https://github.com/calendso/calendso.git main`
2. Then, in the same directory, I ran `railway run npx prisma migrate deploy`
3. In the past this was all I needed to do to update to the latest version.  Now, it fails to build and is not deployed by Railway.

I think it's related to a recent node version change in package.json to >=14.x and react-multi-email, but I cannot be certain.

### Technical details

- Node.js version: v17.1.0
- On Railway

### Build Logs
```20: Pulling from heroku/buildpacks
Digest: sha256:c8fa136b9db7fd3846a6fa0dc4dccbbe65560c3107ca9d907660813300950c48
Status: Image is up to date for heroku/buildpacks:20
20: Pulling from heroku/pack
Digest: sha256:baa29da011c99d1cf5999da0e6c2450fa242d031f66872da8afb126750eec3fa
Status: Image is up to date for heroku/pack:20
===> DETECTING
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
heroku/nodejs-yarn       0.1.5
===> ANALYZING
Previous image with name "registry.railway.app/feeac990-20d4-493f-96fe-52b3ba390f40" not found
===> RESTORING
===> BUILDING
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[Installing Node]
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v17.1.0

[Parsing package.json]
[INFO] Parsing package.json

[Installing yarn]
[INFO] Installing yarn@1.22.17
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v8.1.2 from Node
[INFO] Installing node modules
npm notice 
npm notice New patch version of npm available! 8.1.2 -> 8.1.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.3>;
npm notice Run `npm install -g npm@8.1.3` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: calendso@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.2" from react-multi-email@0.5.3
npm ERR! node_modules/react-multi-email
npm ERR!   react-multi-email@"^0.5.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-11-16T22_57_26_880Z-debug.log
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51```

**Comment by likeaj6** [comment]
Had same issue, Railway is using NPM instead of Yarn for some reason. Resolved by toggling "Experimental buildpacks".
![Screen Shot 2021-11-16 at 9 31 10 PM](https://user-images.githubusercontent.com/13268856/142140612-cadf4eef-abb1-4d37-a5f3-777ea621fa5d.png)

**Comment by jstrellner** [comment]
@likeaj6 Thanks, that almost got me there.  The other thing I had to do was change the node version in package.json to 16.13.0.

**Comment by samuelmaker** [comment]
+1 I had to revert the node version change in the package.json to get railway to deploy again. 
I believe it fails when using node 17.x

**Comment by chug2k** [comment]
sorry for beginner question - the starter on Railway's site still uses 1.0. What's the difference between railway's starter calendso and just going here from HEAD?

**Comment by JakeCooper** [comment]
I've created a PR for this bad boi^^

**Comment by masteradit** [comment]
> Resolved by toggling "Experimental builder".

Thanks @likeaj6! This resolved my issue.

**Comment by baileypumfleet** [comment]
As this is now resolved, please try with the latest version.
