### ISSUE TITLE
TRPCClientError: The column `Webhook.payloadTemplate` does not exist in the current database / The column `Webhook.payloadTemplate` does not exist in the current database, code :-32603

### ISSUE THREAD

**Issue by chug2k** [calendso/calendso#1196]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On the cal.com website, I created a webhook but didn't fill in the payload (I think). Now I'm unable to load the page again - infinite spinner.

### Steps to Reproduce

1. Go to https://app.cal.com/integrations
2. Site doesn't load, check browser console for errors

### Technical details

Console.log from the 500:
```
[{"id":null,"error":{"json":{"message":"The column `Webhook.payloadTemplate` does not exist in the current database.","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"viewer.webhook.list"}}}}]
```

**Comment by baileypumfleet** [comment]
Migration wasn't run on hosted, fixed now.
