### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by storrisi** [calendso/calendso#12]
I'm new to this project and I love it so much already.

Would be awesome to have a docker-compose file in order to start the environment (postgres and so on) and deploy it easily on a server.

**Comment by baileypumfleet** [comment]
Sure, we have a couple of people who are working on that.

**Comment by gonrial** [comment]
Check #7

**Comment by alexanderadam** [comment]
> Check #7

Great. After this is merged, images should be [build and pushed to docker hub](https://hub.docker.com/search?q=calendso&type=image) (maybe via GH actions?).

**Comment by alissonash** [comment]
I don't know if I'm in the right post. Sorry for anything.

After configurations, the application went up correctly, but when trying to login, the message of:

"Incorrect password An error occurred when logging you in. Head back to the login screen and try again. "

`startUp.sh` was used to start the prism and generate the first user, however, even after creating the correct user, I still receive the error message in the password!

Is there any need for further configuration besides creating the user through the `studio prism`?

Can someone help me?

**Comment by PeerRich** [comment]
hey hey, we've launched unofficial docker support: https://github.com/calendso/calendso-docker
