### ISSUE TITLE
Office 365 Integration fails behind NGINX reverse proxy

### ISSUE THREAD

**Issue by matteqa** [calendso/calendso#120]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When running Calendso behind an NGINX reverse proxy, I get the following error after clicking the Add button on the Office 365 Integration:
`Apr 29 23:56:14 s0.rightweb.com.au bash[6543]: http://cal.rightweb.com.au
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]: Error: Unable to determine external url, check server settings
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at handler (/root/calendso/.next/server/pages/api/integrations/office365calendar/add.js:137:13)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at runMicrotasks (<anonymous>)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at async apiResolver (/root/calendso/node_modules/next/dist/next-server/server/api-utils.js:8:1)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at async Server.handleApiRequest (/root/calendso/node_modules/next/dist/next-server/server/next-server.js:64:462)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at async Object.fn (/root/calendso/node_modules/next/dist/next-server/server/next-server.js:56:492)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at async Router.execute (/root/calendso/node_modules/next/dist/next-server/server/router.js:23:67)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at async Server.run (/root/calendso/node_modules/next/dist/next-server/server/next-server.js:66:1042)
Apr 29 23:56:14 s0.rightweb.com.au bash[6543]:     at async Server.handleRequest (/root/calendso/node_modules/next/dist/next-server/server/next* Anything else that you think could be an issue.-server.js:34:504)`

And the following error in chromium developer tools:
`GET https://cal.rightweb.com.au/api/integrations/office365calendar/add 500 (Internal Server Error)
f @ integrations-a9d434636d2817aca795.js:1
onClick @ integrations-a9d434636d2817aca795.js:1
We @ framework.d2e6186d001d2275b0af.js:1
Ye @ framework.d2e6186d001d2275b0af.js:1
(anonymous) @ framework.d2e6186d001d2275b0af.js:1
xr @ framework.d2e6186d001d2275b0af.js:1
Cr @ framework.d2e6186d001d2275b0af.js:1
(anonymous) @ framework.d2e6186d001d2275b0af.js:1
De @ framework.d2e6186d001d2275b0af.js:1
(anonymous) @ framework.d2e6186d001d2275b0af.js:1
Or @ framework.d2e6186d001d2275b0af.js:1
Zt @ framework.d2e6186d001d2275b0af.js:1
Jt @ framework.d2e6186d001d2275b0af.js:1
t.unstable_runWithPriority @ framework.d2e6186d001d2275b0af.js:1
Wl @ framework.d2e6186d001d2275b0af.js:1
Me @ framework.d2e6186d001d2275b0af.js:1
Xt @ framework.d2e6186d001d2275b0af.js:1
`

I have tried changing many things in my nginx configuration but nothing seems to change it.

Here is my current nginx configuration:
`server {
    root            /root/calendso;
    server_name     cal.rightweb.com.au;
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/cal.rightweb.com.au/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/cal.rightweb.com.au/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}
server {
    listen 80;
    server_name cal.rightweb.com.au;
    rewrite ^/(.*)$ https://cal.rightweb.com.au/$1 permanent;
}
server {
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/cal.rightweb.com.au/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cal.rightweb.com.au/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    server_name *.cal.rightweb.com.au;
    rewrite ^/(.*)$ https://cal.rightweb.com.au/$1 permanent;
}
`

### Steps to Reproduce
1. Install calendso server with office 365 api keys
2. Set up nginx reverse proxy
3. Try to add the office 365 integration.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: Brave 89 (chromium)
* Node.js version: v12.22.1

**Comment by emrysal** [comment]
This is possible, but it requires to add the X-Forwarded-Host header to convey the external host.

`proxy_set_header X-Forwarded-Host $host;`

`

**Comment by matteqa** [comment]
Thanks, I swear I tried that before but anyway.

I'm having another issue however, I get this error in the URL after callback: 
AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.

**Comment by emrysal** [comment]
You may have already been able to resolve this; if not, could you share what delegated permissions you have configured in Azure AD?

**Comment by matteqa** [comment]
Calendars.Read
Calendars.ReadWrite
User.Read
User.ReadWrite

All delegated permissions.

**Comment by baileypumfleet** [comment]
Closing this off due to no movement, and the fact that NGINX isn't officially supported by us
