### ISSUE TITLE
Times get cut when extra line in month view

### ISSUE THREAD

**Issue by pedrorrivero** [calendso/calendso#1210]
### Issue Summary
When there is one extra line in the month view the times do not display full height.

### Steps to Reproduce
1. Check January 22

### Technical details

- Browser version: Chrome 96

<img width="1037" alt="Screen Shot 2021-11-24 at 14 32 44" src="https://user-images.githubusercontent.com/52980156/143309486-7090f6c7-2f79-4e06-b468-3127dc2b58f3.png">

**Comment by PeerRich** [comment]
fixed! thank you @zzwt https://github.com/calendso/calendso/pull/1256
