### ISSUE TITLE
Unable to Login - Showing error when adding new user record

### ISSUE THREAD

**Issue by arpitprod** [calendso/calendso#1222]
### Issue Summary

error showing after add id, username, name, email, password in User table.
and Prisma Studio error modal not showing CTA button and full bug & I can't scroll.

<img width="1238" alt="Screenshot 2021-11-26 at 15 51 51" src="https://user-images.githubusercontent.com/19798516/143568928-dccc7043-636e-4c3e-b0b5-fdcf43bb225e.png">

### Steps to Reproduce
1. added new record with id, username, name, email, password in User table

### Technical details

- Browser version: Chrome 96
- Node.js version: v16.13.0

**Comment by programmeddeath1** [comment]
Press ctrl - on the browser to zoom out and see the entire error message.

**Comment by arpitprod** [comment]
Previously It was not working without add id column also. So, I added id manually.
But It's working fine now as you guided.
thanks
