### ISSUE TITLE
Jumping in years by selecting a day in a future month

### ISSUE THREAD

**Issue by flemming-petersen** [calendso/calendso#1226]
### Issue Summary

By clicking on a day in a future month, the year will be increased by one year. But only when the selected month is not in the current year.

### Steps to Reproduce

The video will explain it good.
https://www.loom.com/share/3aec0f617c544366878efaa0d4d7c478

### Technical details
Browser: Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by narzero** [comment]
+1

**Technical details**
Browser:  96.0.4664.45 (Official Build) (64-bit)
Cal version: 1.1

**Comment by artistro08** [comment]
Got this issue too. Seems to be tied to the new year coming up
