### ISSUE TITLE
Error during compilation 'TypeError: (0 , next_auth_client__WEBPACK_IMPORTED_MODULE_2__.csrfToken) is not a function'

### ISSUE THREAD

**Issue by jacobocode** [calendso/calendso#123]
Found a bug? Please fill out the sections below. 👍

### Hi I got an Error during compilation (npm run dev)

TypeError: (0 , next_auth_client__WEBPACK_IMPORTED_MODULE_2__.csrfToken) is not a function
    at Function.exports.modules../pages/auth/login.tsx.Login.getInitialProps (C:\Users\BA\Documents\cnext\server\pages\auth\login.js:188:81)

### Steps to Reproduce
I installed and registered everything like you wrote in instruction.
except yarn, couse I had problem with it so I use npm instead

### Technical details
* Browser version: Google chrome 90.0.4430.93
* Node.js version 14.15.0
* npm 6.14.8

**Comment by jacobocode** [comment]
This works for me:
login.tsx
import { getCsrfToken } from 'next-auth/client'

Login.getInitialProps = async (context) => {
    const csrfToken = await getCsrfToken(context)
  return {
    csrfToken,
  }
}

**Comment by emrysal** [comment]
@baileypumfleet Bugfix PR pending, when I was testing webpack5, at no point was my session invalidated which let this one slip through the cracks.
