### ISSUE TITLE
Date is off by 1 day when scheduling appointments on cal.com

### ISSUE THREAD

**Issue by sec0ndhand** [calendso/calendso#1236]
### Issue Summary

When rescheduling an appointment, the day is off by one day:
![Wrong Date](https://user-images.githubusercontent.com/13591749/144140167-821678a9-8651-4a4b-9349-11e8c89fc72e.gif)

### Steps to Reproduce

1. Schedule an event as a viewing user
2. Reschedule the event as the cal.com event organizer
3. Observe the date being inaccurate by +1 day

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
When I click on the 8th of December, I expect the 8th of December to be shown.  What I experienced was that it showed the 9th of December.

### Technical details

- Browser version: Chrome 96
- Node.js version (this was on cal.com so I don't know what version is ran there)
- I am in mountain standard time (MST) and this is the JS time in the console: 

```javascript
new Date()
Tue Nov 30 2021 15:50:05 GMT-0700 (Mountain Standard Time)
```

**Comment by dmonn** [comment]
Experiencing the same with inaccuracies being up to +5 days

https://www.loom.com/share/937cc55f352e4bcbabd04d74bef67f3c

Link: https://cal.com/dom/the-mentorcruise-podcast?date=2021-11-30%2B0100

## Technical details

Browser version: Chrome 96
I am in Central European Standard Time (CET) and this is the JS time in the console:

```
new Date()
Wed Dec 01 2021 19:55:05 GMT+0100 (Central European Standard Time)
```
