### ISSUE TITLE
feedback.calendso.com has been down for a week

### ISSUE THREAD

**Issue by matteqa** [calendso/calendso#125]
I was looking through a closed issue about CalDAV support and it links to feedback.calendso.com to vote on the issue. The website however returns Vercel 404: Deployment not found.

**Comment by emrysal** [comment]
I believe feedback.calendso.com has fully moved now to Github discussions, hense why it's down

**Comment by emrysal** [comment]
CalDAV support is on the roadmap; https://github.com/calendso/calendso/discussions/62

**Comment by baileypumfleet** [comment]
That’s correct, we’ve gotten rid of feedback.calendso.com in order to centralise everything in GitHub

**Comment by PeerRich** [comment]
let's redirect feedback.calendso.com to https://github.com/calendso/calendso/discussions
