### ISSUE TITLE
Configureable "frequency" between event starts (in handleAvailableSlots)

### ISSUE THREAD

**Issue by jippi** [calendso/calendso#1253]
### Describe the solution you'd like

Today calendso uses the `eventLength` to compute the possible start times for booking an event (e.g. a 60min event will start at 10:00, 11:00, 12:00, 13:00 etc by default) 

Its however not possible to configure the `frequency` in `handleAvailableSlots` so I can offer more granular start times for a 1 hour meeting (e.g. 10:00, 10:15, 10:30, 10:45 etc) since the frequency always default to the `xx:00` time of day.

In my case, my availability daily is from 09:30 to 17:30 - but all my 1h meetings are not bookable until 10:00 due to this issue, making 1h meeting from 09:30 to 10:30 impossible to book in the current scenario 

### Describe alternatives you've considered

Allow a customizable `frequency` in `handleAvailableSlots` / `getSlots` by event, so as a user I can say `this 1h meeting can be booked in 15min intervals like 10:00, 10:15, 10:30, 10:45 and 11:00 if availability is free`

My current work-around for this is to change the code like this, allowing for at 15min or smaller intervals depending on the event length, which satisfies booking in 15, 30, 45, 60 and 90 min length for me with proper granularity on start time

Note this patch is not perfectly correct, in the example where I have a 2h event length, and a meeting scheduled from 14:00 to 15:00, the available time slot 15:15, 15:30 and 15:45 are skipped, and the UI only shows 16:00 as the next available start time (https://share.getcloudapp.com/WnukgKYE)

```diff
diff --git a/lib/hooks/useSlots.ts b/lib/hooks/useSlots.ts
index 7e02af4..e4915e0 100644
--- a/lib/hooks/useSlots.ts
+++ b/lib/hooks/useSlots.ts
@@ -102,7 +102,7 @@ export const useSlots = (props: UseSlotsProps) => {
   const handleAvailableSlots = async (res: Response) => {
     const responseBody: AvailabilityUserResponse = await res.json();
     const times = getSlots({
-      frequency: eventLength,
+      frequency: Math.min(15,eventLength),
       inviteeDate: date,
       workingHours: responseBody.workingHours,
       minimumBookingNotice,
```

### Additional context

Thanks for a great Open Source product!

**Comment by emrysal** [comment]
Hi @jippi - I linked the PR that implements this "interval" feature. Have a look and see if this will solve your issue (feel free to unlink if you feel it differs from your requirements)

**Comment by jippi** [comment]
Hi @emrysal 

I've tried out your PR on my local installation, and it perfectly fixes my use-case as described. 

I do however think the default value of event length is not very intuitive, and a default value of 15min or a similar lower value would be "path of least surprise" for most users (based on my own experience).

The reason for this is that I want to optimize my calendar generally for "packed" days where meetings can be scheduled back to back no matter the duration of each meeting, where the default behavior would artificially suppress available time slots when using event duration for the interval.

Since it's configurable, I don't care too much, I'm quite happy with how fast you picked this up in the first place, it was basically the only blocker for me fully adopting for my scheduling needs! :) 

Side note: Would be nice with a "buffer between events" configuration too at some point, so I could say "pack my calendar, but always prevent back-to-back meetings and leave X time between bookings" - but that's a huge tangent from this ticket.

Thanks again for speedy turnaround and responsiveness to my ticket!

**Comment by emrysal** [comment]
The reason I kept intervals to default to the unintuitive event length is due to backwards compatibility reasons; it works for a large chunk of users (I'd say 90% is happy using the event length) and as such is probably a better default than something like 15m. 

beforeBuffer is my next todo coincidentally; so that's not far off! designs are already done for that.

**Comment by emrysal** [comment]
The reason I kept intervals to default to the unintuitive event length is due to backwards compatibility reasons; it works for a large chunk of users (I'd say 90% is happy using the event length) and as such is probably a better default than something like 15m. 

beforeBuffer is my next todo coincidentally; so that's not far off! designs are already done for that.
