### ISSUE TITLE
Error: The table `public.users` does not exist in the current database.

### ISSUE THREAD

**Issue by herberthobregon** [calendso/calendso#126]
### Issue Summary
Message: Error in Prisma Client request: 

Error: The table `public.users` does not exist in the current database.

### Steps to Reproduce
1. update DATABASE_URL
2. Open prisma studio
3. load schema
4. Select users
5. error

Following this guide
https://docs.calendso.com/docs/installation

**Comment by baileypumfleet** [comment]
Have you tried running `npx prisma db push —preview-feature` again?

**Comment by herberthobregon** [comment]
Thank you! now it works!
