### ISSUE TITLE
There is no validation on input fields while booking (Try Demo)

### ISSUE THREAD

**Issue by iamtabrezkhan** [calendso/calendso#127]
When I click on `Try demo` button it takes me to schedule a meeting, but at the very last step (i.e. when I fill in the details and click on Confirm button), I am able to proceed without even filling anything in the input fields. There is no validation check on the input fields.

Please confirm if this has been addressed or if anyone is working on this?

**Comment by baileypumfleet** [comment]
Duplicate issue of #43
