### ISSUE TITLE
Location options are repeatedly added to Location Dropdown

### ISSUE THREAD

**Issue by manoj-manoharan** [calendso/calendso#1302]
### Issue Summary

Every time I select a option and then cancel option from Location Dropdown 
Link or In person meeting, Phone call these options are appended repeatedly to the Select Location dropdown options
I tried in my local setup and in cal.com

### Steps to Reproduce

1.  Edit Event Type
2. Select Location
3. Select Any option (eg:  Google Meet )
4. Cancel

### Technical details

- Browser version: 96.0.4664.93
- Node.js version: 
![Screenshot 2021-12-13 at 9 45 05 PM](https://user-images.githubusercontent.com/19284057/145928515-3bbe2c94-f3b8-441c-9c8e-b3e15e171e55.png)
14.15.0

**Comment by manoj-manoharan** [comment]
I have created a [fix for this issue](https://github.com/manoj-manoharan/calendso/commit/e859535f241035966bbfe9783502b686c6421cb6), but not able to create a pull request

**Comment by manoj-manoharan** [comment]
When I try to create a pull request `Create Pull Request` button is disabled

**Comment by zomars** [comment]
@manoj-manoharan you need to add a title to the PR

**Comment by manoj-manoharan** [comment]
Thank you for creating pull request 🙏🏻. I feel embarrassed🤦🏻‍♂️
