### ISSUE TITLE
Teams' about text not showing up on their page

### ISSUE THREAD

**Issue by austinbrown101** [calendso/calendso#1305]
### Issue Summary

After creating a team and filling out the Team's "About" section, that text doesn't show up on the team link under the team's name like it does with a person

### Steps to Reproduce

1. Create team and fill out about section
2. Go to team's link

### Technical details

- Browser version: Edge 96
- I'm running the self-hosted docker version

![Edit Team](https://user-images.githubusercontent.com/20783165/145967777-20f898f1-cb90-469c-aba2-4122e1db2730.jpg)
![Team Page](https://user-images.githubusercontent.com/20783165/145967778-3427e5ed-9875-4653-964a-269330863a2a.jpg)

**Comment by ConnorGargano** [comment]
Hi @austinbrown101,
Thanks for sharing this with us, I will get this raised to our team now!

**Comment by austinbrown101** [comment]
Works great now, thanks for the fix
