### ISSUE TITLE
If i try to schedule a meeting for next month calendar goes bananas

### ISSUE THREAD

**Issue by Graviis** [calendso/calendso#1331]
### Issue Summary

I can't schedule a meeting for the next month, the year start doing year+1

### Steps to Reproduce

1. Go to any user https://cal.com/jamie
2. Go to the next month
3. Click on any day.

![Kapture 2021-12-16 at 15 35 25](https://user-images.githubusercontent.com/21148423/146391657-379313b6-e9aa-48e1-9c51-cd1423e478a9.gif)

### Technical details

- Browser version: Chrome

**Comment by Graviis** [comment]
I've been checking and the `DatePicker` is not working properly. I'll try to fix it.

**Comment by Graviis** [comment]
i saw a fix here https://github.com/calendso/calendso/commit/a3bd22634772bdb7c073cb2cf2488e2a54696e81 no sure why it's necessary all the new code

**Comment by emrysal** [comment]
@Graviis The year change was only one part of that PR, it was also fixing a few other issues and a few undocumented bugs, one of the main ones making sure that the dayjs instantiation is system-timezone-independant at all times (primarily to make tests pass).

**Comment by Graviis** [comment]
Alright, so im gonna close the issue and PR
