### ISSUE TITLE
Can't reschedule appointments on cal.com

### ISSUE THREAD

**Issue by sec0ndhand** [calendso/calendso#1337]
### Issue Summary

When rescheduling, I cannot complete the task:
![Cant_reschedule](https://user-images.githubusercontent.com/13591749/146441344-b363a1b6-feb8-4fb1-80e4-d0732889deb2.gif)

### Steps to Reproduce

1. Schedule a meeting
2. attempt to reschedule

I expected to be able finish filling out the reschedule form.

### Technical details

Chrome 96 on a mac.

**Comment by ConnorGargano** [comment]
Hi @sec0ndhand 
Looks like you are pressing reschedule before inputting the required information, can you give it another go please but this time filling in the name, email ect before pressing reschedule

**Comment by sec0ndhand** [comment]
That's the point, If I am rescheduling an appointment, the information is already in the database, it should pre-populate everything EXCEPT the time.

**Comment by shubhamV123** [comment]
Hey @ConnorGargano Can I look and fix this issue?
