### ISSUE TITLE
Incorrect time produced when adding new event to calendar via Google link from confirmation screen

### ISSUE THREAD

**Issue by josephjacks** [calendso/calendso#134]
### Issue Summary

Noticed a bug when booking on my iPhone (chrome): I booked someone for a meeting from their Calendso link, and after seeing the confirmation screen when completing the booking, I then clicked the "G" to add the event to my calendar, which it did, but for an hour earlier than specified and for an entire hour (the meeting was booked for only 15 min). I noticed that the correct time was automatically added to my calendar independent of this.

**Comment by PeerRich** [comment]
saw this bug happen once before @baileypumfleet maybe with the most recent update it broke

**Comment by emrysal** [comment]
@PeerRich Seems to have just gone unnoticed for a long time as it is not very apparent, but dates= never worked (Google eventedit just made the dates up as it went along..)

PR with fix: #136
