### ISSUE TITLE
Error:  Invalid `prisma.user.findUnique()` invocation:  connect ECONNREFUSED ::1:55859 when trying to set up a new calendso instance

### ISSUE THREAD

**Issue by devotionsolutions** [calendso/calendso#1371]
I'm getting an Error:  Invalid `prisma.user.findUnique()` invocation:  connect ECONNREFUSED ::1:55859 when trying to set up a new calendso instance

### Steps to Reproduce

1. Follow development setup as described in README file
2. When trying to login with my new user, I'm getting a generic error saying "Something went wrong". I'm not able to login in calendso
3. If I try to access another url, like http://localhost:3000/signup, I'm getting the following error: Error:  Invalid `prisma.user.findUnique()` invocation:  connect ECONNREFUSED ::1:55859
4. I'm getting similar errors with Prisma Studio, so I'm suspecting that this is related with my database:
"A non-recoverable error has occurred and Studio has to be restarted. Please consider reporting this error to us by opening an issue on GitHub and attaching the error details."
Unable to process `count` query undefined
5. I'm able to connect to my database, browse the schemas and also create a new user

I was expecting to setup a local working version of calendso before setting up an online version.

**Comment by flemming-petersen** [comment]
Did you copied the .env.example to .env?

**Comment by devotionsolutions** [comment]
yes, I did that

**Comment by devotionsolutions** [comment]
I think I'm missing something here. I've also followed the instructions here: https://hub.docker.com/r/calendso/calendso and when I run  docker-compose exec calendso npx prisma studio and open the prisma studio, I'm now seeing this error:
Message: Error in Prisma Client request: Invalid `prisma.user.findMany()` invocation: The table `public.users` does not exist in the current database.

Am I missing something related to postgresql or the migrations maybe?

**Comment by zomars** [comment]
Can you details the steps you followed? There are multiple options on the README.

**Comment by devotionsolutions** [comment]
Invalid issue. I was misleading a step during the setup
