### ISSUE TITLE
Requests to stripe generated on every single click in the app

### ISSUE THREAD

**Issue by wetneb** [calendso/calendso#1374]
### Issue Summary

When I browse someone's availability on cal.com, my browser makes many requests to `https://m.stripe.com/6`. Those can be seen by opening the web developer tools and looking at the network tab.

This seems related to this:
https://stackoverflow.com/questions/45718026/stripe-js-making-duplicate-requests-new-requests-on-state-change

### Steps to Reproduce

1. Went to any cal.com profile
2. Open your Dev tools, go to the network tab
3. Click around in the app, checking out availability for various days
4. Every time you change day, a new request to Stripe is made

### Technical details

- Browser version: Chromium, Firefox

**Comment by PeerRich** [comment]
we will look into this!

**Comment by zomars** [comment]
This is expected behavior, Stripe uses this data to detect possible fraudulent transactions. We can opt-out of this at the cost of increased fraud risk. We should discuss if it's worth the annoyance.

**Comment by wetneb** [comment]
It is pretty unclear to me why Stripe needs to track the people who want to meet with me, since they will never have to interact with Stripe through Cal.com. I am the one paying for the app, not them.

**Comment by zomars** [comment]
It's part of our paid bookings integrations with Stripe. You can add your Stripe account on the integrations, put a price on a booking and charge your customers to book you. Stripe uses this data to prevent frauds on the payment step.

**Comment by wetneb** [comment]
I see! It would be nice if the tracking could be disabled if the Stripe integration has not been enabled.

**Comment by zomars** [comment]
Agreed we can improve this even further and add it to the backlog and be prioritized accordingly. You can read more about [Stripe's fraud detection here](https://stripe.com/docs/disputes/prevention/advanced-fraud-detection).

**Comment by wetneb** [comment]
The prioritization of this is your call, of course. But since your app is marketed as an open source alternative to another service, I would expect many of your users to be also privacy-conscious, and therefore care about this. Also the mitigation does not seem difficult to implement at all.

**Comment by kosso** [comment]
Indeed. Why does this request keep getting made on pages that don't even use stripe.  

They seem to be completely tracking all usage of our entire app, and not just the pages with payments.

How to stop this?
