### ISSUE TITLE
Tracking requests made on every single click in the app

### ISSUE THREAD

**Issue by wetneb** [calendso/calendso#1375]
### Issue Summary

When I browse someone's availability on cal.com, my browser makes many requests to `https://t.calendso.com/api/v1/event`. Those can be seen by opening the web developer tools and looking at the network tab.

uBlock Origin blocks those requests, suggesting that those requests are only there to track user behaviour rather than implementing a feature.

As a user, I do not want to point my colleagues to an app that does such tracking. It is also detrimental to the performance of the app.

### Steps to Reproduce

1. Went to any cal.com profile
2. Open your Dev tools, go to the network tab
3. Click around in the app, checking out availability for various days
4. Every time you click on things, a new request to `https://t.calendso.com/api/v1/event` is made.

### Technical details

- Browser version: Chromium, Firefox

**Comment by emrysal** [comment]
This is in progress, we had a look at the event and we don't actually use it for anything, so it'll be removed shortly.
