### ISSUE TITLE
Is documentation missing?

### ISSUE THREAD

**Issue by andretti1977** [calendso/calendso#14]
Am i missing documentation? Is [https://docs.calendso.com/docs/](https://docs.calendso.com/docs/) a draft?

**Comment by baileypumfleet** [comment]
Yes, the documentation is very basic at the moment, as we're looking for people to work own the documentation. If you're interested in helping out, please join our [Slack](https://join.slack.com/t/calendso/shared_invite/zt-mem978vn-RgOEELhA5bcnoGONxDCiHw).
