### ISSUE TITLE
Emails are always in the bookers language

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#1495]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Right now, the email that is being sent to both receiver and booker are always in the bookers language.

The emails need to be separate languages: the language of the booker and the language of the receiver. If no language is detected on the client, default to English

### Steps to Reproduce

1. change your user agent to another language
2. book your own link

**Comment by Jojo14234** [comment]
Hi, I just encountered this issue again (happened when the person that booked did so in another language as the one i have set as my profile's language...).

**Comment by sternbj** [comment]
same issue, but there is also no setting for the language, so it must take the profile language, right? But it is in deed not possible to create multilingual invitations
