### ISSUE TITLE
Background Color Changing

### ISSUE THREAD

**Issue by sydwardrae** [calendso/calendso#1517]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

From a cust: I just signed up for the cal.com trial. I’m embedding an iframe on our site and everything works great except for the background color changes from page to page. The first page is #F8F8F8 and on the second page the background color changes to #F5F5F5

**Comment by sydwardrae** [comment]
@PeerRich

**Comment by PeerRich** [comment]
will look into it! thank you for flagging

**Comment by sydwardrae** [comment]
hey @PeerRich here's the video from the customer as well to provide more context : https://files.swansonking.com/HFvRnjVr.mp4

**Comment by PeerRich** [comment]
fixed! really helpful video

**Comment by mjking** [comment]
Here is one more spot where the background color is different. On the confirmation page https://files.swansonking.com/xEU2DgXx.jpg

**Comment by PeerRich** [comment]
> Here is one more spot where the background color is different. On the confirmation page https://files.swansonking.com/xEU2DgXx.jpg

good catch. will fix
