### ISSUE TITLE
Cannot destructure property 'client_id' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by krumware** [calendso/calendso#1518]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The calendso/docker automated build started failing last night after the automatic submodule update.
This is the error:

```
#13 71.59 > Build error occurred
#13 71.59 TypeError: Cannot destructure property 'client_id' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
#13 71.59     at Object.491 (/app/.next/server/chunks/9241.js:72:20)
#13 71.59     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
#13 71.59     at /app/.next/server/pages/auth/signup.js:32:80
#13 71.59     at Function.__webpack_require__.a (/app/.next/server/webpack-runtime.js:98:13)
#13 71.59     at Object.8444 (/app/.next/server/pages/auth/signup.js:11:21)
#13 71.59     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
#13 71.59     at __webpack_exec__ (/app/.next/server/pages/auth/signup.js:626:39)
#13 71.59     at /app/.next/server/pages/auth/signup.js:627:141
#13 71.59     at Function.__webpack_require__.X (/app/.next/server/webpack-runtime.js:182:21)
#13 71.59     at /app/.next/server/pages/auth/signup.js:627:47 {
#13 71.59   type: 'TypeError'
#13 71.59 }
```

It looks like there were several changes related to authentication, so perhaps a type issue was introduced?

linking with https://github.com/calendso/docker/issues/72

### Steps to Reproduce

Repo admins can find the run logs here:
https://github.com/calendso/docker/runs/4822358078?check_suite_focus=true

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
i wonder if this has something to do with https://github.com/calendso/calendso/pull/1192 ? @deepakprabhakara @zomars timing wise it could fit

**Comment by zomars** [comment]
We need to make sure that `GOOGLE_API_CREDENTIALS` is defined.
