### ISSUE TITLE
add parameters for selected dates

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#152]
### Is your proposal related to a problem?

right now you can't send someone a link with a predefined date

### Describe the solution you'd like

add parameters for selected dates

### Additional context

this:

![image](https://user-images.githubusercontent.com/8019099/117132942-79cdd200-ad9b-11eb-9d4e-8fbeea70fd65.png)

should have:

https://calendso.com/rick/quick-chat?month=2021-05&date=2021-05-05

**Comment by baileypumfleet** [comment]
One key thing to make sure of here is that for instance if I'm given a link to book someone at 2pm UTC, that me (who's in UTC+1) isn't shown 2pm, and instead is shown 3pm

**Comment by femyeda** [comment]
Done.
