### ISSUE TITLE
GitHub: fix checks

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#1527]
for some reason, the 4th check is never finishing and blocks CI

![image](https://user-images.githubusercontent.com/8019099/149656547-eed6ae95-553b-4f61-bc80-d48c42197c8a.png)

**Comment by zomars** [comment]
It seems this was introduced in #1504

**Comment by zomars** [comment]
Fixed by [updating repo settings](https://stackoverflow.com/a/68988320/6297100)
