### ISSUE TITLE
Ask reasons for account deletion

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#1531]
when clicking "delete account"
![image](https://user-images.githubusercontent.com/8019099/149770647-3576ce77-6e57-4f3a-9ff8-f1ea3155cf43.png)
.. open a modal and ask for reasons:

- I don't need a scheduling link anymore
- It's too expensive
- Something is broken => show textfield: "What's not working?"
- I found a better product => show textfield: "Which app and what are they doing better?"
- Other

simple list of radio buttons should be fine:
![image](https://user-images.githubusercontent.com/8019099/149770953-2f404105-3168-421b-bf30-129e036be155.png)

**Comment by alishaz-polymath** [comment]
Where do I send the submitted form/reasons?

**Comment by PeerRich** [comment]
help@cal.com
