### ISSUE TITLE
Customer Exit Survey

### ISSUE THREAD

**Issue by sydwardrae** [calendso/calendso#1535]
### Is your proposal related to a problem?

Customer Exit Survey (whenever they delete their account)

### Describe the solution you'd like

What plan of cal.com were you subscribed to?   

-     Free
-     Pro
-     Enterprise
-     Infrastructure

What is your primary reason for leaving? 

-     Price
-     Service
-     No longer needed
-     Not enough ROI
-     Missing features
-     Competitor
-     Other

If improvements were made, would you consider coming back and giving cal.com another try?

-     Yes
-     No

How else can we improve?

**Comment by PeerRich** [comment]
done!
