### ISSUE TITLE
Support for new line in event description

### ISSUE THREAD

**Issue by Bhupesh-V** [calendso/calendso#1590]
### Is your proposal related to a problem?

So currently all the description text is continuous, even when I add new lines (or separate them in different paragraphs)

<img width="701" alt="Screenshot 2022-01-23 at 12 55 12 PM" src="https://user-images.githubusercontent.com/34342551/150668771-7d5a740c-5d4e-482c-b8af-e9d2173aa62a.png">

<img width="1217" alt="Screenshot 2022-01-23 at 12 53 36 PM" src="https://user-images.githubusercontent.com/34342551/150668727-7f115828-1472-4641-b9d2-6a99faea791d.png">

### Describe the solution you'd like

It would be nice if the event description respects newline characters

### Describe alternatives you've considered

Tried adding HTML `<br>` didn't work 😅 

### Additional context

N/A

**Comment by milospuac** [comment]
Hey Bhupesh! Thanks for the suggestion. I will bring this to the attention of our design team.
