### ISSUE TITLE
Create one-time use links

### ISSUE THREAD

**Issue by Nevon** [calendso/calendso#16]
Currently Calendso exposes a way for anyone to book a slot in your calendar. For my use-case, I would like to be able to create a one-time use link that I can send to someone and have them book a slot via. Essentially to just to be able to generate a token with an expiry, and then to have the application verify that the token is still valid before accepting the booking.

**Comment by baileypumfleet** [comment]
Hi Nevon, thanks for your suggestion. I've added it to our feature voting system so we can gauge interest in this before confirming that we're going to create this ourselves. You can find the feature suggestion here: https://feedback.calendso.com/posts/12/single-use-booking-links

I'll close this one off for now, and re-open it either if this gets enough interest for us to build it ourselves, or if someone wants to take this on themselves.

**Comment by TheBestMoshe** [comment]
@baileypumfleet The feedback link provided does not work. Is this being tracked anywhere?
