### ISSUE TITLE
chinese translation not being picked up correctly

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#1605]
for some reason the zh-CN (chinese simplified) file is not being picked up by next-i18next

![image](https://user-images.githubusercontent.com/8019099/150828686-cfe2f109-6673-4df9-a0c1-afbad3452131.png)
![image](https://user-images.githubusercontent.com/8019099/150828715-342dfb83-b585-4749-8854-7a910a26eef7.png)
![image](https://user-images.githubusercontent.com/8019099/150828735-5a6a3a80-0568-4d73-928d-3672b326215b.png)

**Comment by PeerRich** [comment]
@isaachinman [mentioned](https://github.com/isaachinman/next-i18next/issues/279#issuecomment-1021147473):

> The `next-i18next` package doesn't touch locales at all, anymore. They are handled directly by NextJs and i18next. Happy to help debug if you provide more info, but ultimately the solution will lie somewhere outside `next-i18next`.


@steven-tey maybe you can help? It seems like this is a next bug?

**Comment by leerob** [comment]
zn-CH is working with Next.js i18n + Nextra here: https://swr.vercel.app/zh-CN/docs/getting-started

**Comment by zzwt** [comment]
Did some quick investigation. The zh-CN file DOES picked up by Next.js i18n, however, the zh-CN file is not fully translated. Full translation have about 600 items but the zh-CN only have about 170 items translated as of 27/1/2022 and 359 items translated in latest update as the time of writing.

**Comment by PeerRich** [comment]
but even the things that are translated are not shown, right?

**Comment by zzwt** [comment]
I understand Chinese, and the one get translated DOES show. 
![image](https://user-images.githubusercontent.com/12154828/151470767-e92def59-788d-4ae1-aef8-d6063a698c00.png)

**Comment by PeerRich** [comment]
ahh perfect!!

**Comment by PeerRich** [comment]
it seems like its working then!
