### ISSUE TITLE
Attendee can't accept invitation directly from their Gmail

### ISSUE THREAD

**Issue by HanBaichuan** [calendso/calendso#1621]
### Is your proposal related to a problem?

Less of a problem, but more of an inefficiency:
Attendee's confirmation Email should include this "widget" below, allowing the attendee to accept the invitation within the Email. Otherwise, they need to go to their Google Calendar, find the new event, and choose "Yes" to the question "Going?".

![example1](https://user-images.githubusercontent.com/4997158/151197930-419a5277-c962-4e98-b688-16152d6705b4.png)

### Describe the solution you'd like

When scheduling directly through Google Calendar or Calendly, the attendee gets that widget in their Email. I was hoping Calendso can do the same, or something similar (maybe just a hyperlink that's equivalent to clicking "Yes"?).

### Describe alternatives you've considered

Is it related to attendee not receiving the invite.ics file? Apologize if I should have done more researches. I'm new to Calendso and TS, but loving this project and wish to learn and add this feature myself. Can I keep this post here and update whenever I have new findings?

**Comment by milospuac** [comment]
Hi there. We always encourage our users to send us features and design flaws, but I am not sure what you are trying to achieve here. Are your teammates all using Google Calendar integration and participation check is something that is necessary?

**Comment by HanBaichuan** [comment]
@milospuac Thank you for your reply! I might have imagined something wrong:

I thought the participation check is necessary for 2 reasons:
1) The event box appears with a solid blue colour on the calendar, clearly indicating it's a confirmed meeting.
2) Only events accepted will send notification alert before the meeting. 

I think I was wrong on the second point. I just tested that even unaccepted events send notifications. Now looking at my feature request again, maybe it wasn't something vital if it's just making the event box solid blue. Perhaps I should close this thread?

**Comment by milospuac** [comment]
I respect your personal preference, it's just that I don't think we would revisit the design of the event box anytime soon. However, do let me know if you have more questions or suggestions.

**Comment by HanBaichuan** [comment]
Thank you @milospuac! I'm closing this issue now
