### ISSUE TITLE
NaN values are shown when creating new event types under your name

### ISSUE THREAD

**Issue by miguelnietoa** [calendso/calendso#1623]
### Issue Summary

When you try to create event types **under your name**, some NaN values are shown in the modal. The creation of event types under a team works properly.

### Steps to Reproduce

1. Login
2. Enter to Event Types tab (`/event-types`)
3. Click on "New event type" button and select your name
4. You can see the NaN values

![image](https://user-images.githubusercontent.com/39246879/151238523-cd593220-f9f0-405d-be35-1171250db933.png)

I think this bug was introduced by the PR #1604 

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/8RJH8
- Node.js version: `14.17.0`

**Comment by miguelnietoa** [comment]
I can work on solving this.

**Comment by sydwardrae** [comment]
Hey there, Miguel! Thanks so much for your request - our team received it and will get back to you as soon as we can! Thank you!

**Comment by sydwardrae** [comment]
Hey there Miguel! Thanks so much for bringing this to our attention - let us know what you need along the way.
