### ISSUE TITLE
ability to upgrade from within the app vs. cal.com/upgrade

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#1631]
### Is your proposal related to a problem?

right now cal.com/upgrade leads to a few problems, namely accounts sometimes are not associated with the stripe billing.

### Describe the solution you'd like

be able to upgrade/downgrade from within app.cal.com

### Describe alternatives you've considered
 
add an email parameter and prefill the email: cal.com/upgrade?email=peer@example.com

**Comment by alishaz-polymath** [comment]
I'd recommend having the upgrade/downgrade from app.cal.com as that's the standard practice and is a smooth flow. Should be accessible from settings/billing
