### ISSUE TITLE
Calendar UI Bug

### ISSUE THREAD

**Issue by surjithctly** [calendso/calendso#168]
The last column is hidden when the month is too long like May 2021. See: https://calendso.com/rick/quick-chat

![image](https://user-images.githubusercontent.com/1884712/117416357-23ad7b80-aece-11eb-88ac-899e3e5756b4.png)

**Comment by jasmeetsohal** [comment]
I've investigated the issue and It seems the ```md:max-h-96``` css class getting the remaining date round grids hidden. I just updated the class to ```md:max-h-97``` it fixes the issue. 
![image](https://user-images.githubusercontent.com/20149200/117485991-b3166580-af86-11eb-9814-38c0124b82e6.png)
##### Note - These changes I've made on the browser not in the actual code base.

**Comment by jasmeetsohal** [comment]
@PeerRich 
The issue seems already fixed in the ```main branch```. I been testing through the issue on local development environment. 

![image](https://user-images.githubusercontent.com/20149200/117569225-44e6b580-b0e2-11eb-8b40-2b09c7368eb6.png)
