### ISSUE TITLE
Calendso totally crashing on login

### ISSUE THREAD

**Issue by bennetfabian** [calendso/calendso#174]
### Issue Summary
Calendso crashes after trying to login. No matter if dev or production, it just crashes but may be a NodeJS issue as I think no file of Calendso's code is mentioned in crash error message.

### Steps to Reproduce
1. Clone calendso from Repo
2. Setup database, Google Token, Azure Token
3. Create user in database
4. `yarn dev`, open localhost:3000 in browser and try to login. After submitting it crashes.

### Technical details
* Browser version: [WhatsMyBrowser](https://www.whatsmybrowser.org/b/0W9P6)
* Node.js version: v16.1.0
* Platform: macOS Big Sur 11.4 Beta 2
* Yarn version: 1.22.10

---
Message after crashing:
```
/usr/local/Cellar/node/16.1.0/bin/node[53742]: ../src/node_http_parser.cc:567:static void node::(anonymous namespace)::Parser::Initialize(const FunctionCallbackInfo<v8::Value> &): Assertion `args[3]->IsInt32()' failed.
 1: 0x104a841a8 node::Abort() [/usr/local/Cellar/node/16.1.0/bin/node]
 2: 0x104a84031 node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/Cellar/node/16.1.0/bin/node]
 3: 0x104a9c9bd node::(anonymous namespace)::Parser::Initialize(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/Cellar/node/16.1.0/bin/node]
 4: 0x104c13c7a v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/Cellar/node/16.1.0/bin/node]
 5: 0x104c13348 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/Cellar/node/16.1.0/bin/node]
 6: 0x104c12a1f v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/Cellar/node/16.1.0/bin/node]
 7: 0x10523d819 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/Cellar/node/16.1.0/bin/node]
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bennetfabian** [comment]
NodeJS may be the version. Could anyone tell me a NodeJS version in which it's working so I could check on my machine?

**Comment by baileypumfleet** [comment]
I've got v12.19.0 on my MacBook and it works, I believe my Mac is on v14. Really not sure why you're facing this, I haven't heard from anyone else about this.

**Comment by emrysal** [comment]
Could try giving node more memory using `--max-old-space-size=`. That said it Calendso runs fine on a dev box with 1G ram on v15.14.0.

**Comment by bennetfabian** [comment]
> I've got v12.19.0 on my MacBook and it works, I believe my Mac is on v14. Really not sure why you're facing this, I haven't heard from anyone else about this.

Well, then the issue may actually be related to my NodeJS version. Gonna try v14 or v15 next to further "investigate".

**Comment by bennetfabian** [comment]
> Could try giving node more memory using `--max-old-space-size=`. That said it Calendso runs fine on a dev box with 1G ram on v15.14.0.
> 
> @baileypumfleet He's running v16, may be related to that, v16 became latest on the 21th of April.

Thanks for your solution approach. Still crashes with 4096 as well as with 6144.

> Well, then the issue may actually be related to my NodeJS version. Gonna try v14 or v15 next to further "investigate".

Gonna try this now and then I'll come back with the result.

**Comment by bennetfabian** [comment]
> @bennetfabian This seems to be a recurring issue when nodejs does a major update, try deleting yarn.lock, run yarn and then yarn dev?

Also tried this, didn't work either. It increasingly seems like it has to do with the version of Node I got.

**Comment by bennetfabian** [comment]
@baileypumfleet @emrysal As expected the issue has to be related to NodeJS v16.1.0. Just installed NodeJS v14 via homebrew on macOS and it works perfectly as expected.

Maybe it's something we have to keep an eye on and until it works with v16 someday maybe we should add a little warning to the README. What do you guys think should be done about this?

**Comment by bennetfabian** [comment]
![image](https://user-images.githubusercontent.com/41294690/117509301-47ce9280-af8a-11eb-9dac-c512027e0214.png)
Maybe just add a max supported node version in brackets

**Comment by emrysal** [comment]
Following is my personal opinion on the right path of addressing this:

I'd hold off on any max supported until this issue has been confirmed by others. When this has been confirmed by others, a WARNING should be added to the readme. simultaniously, the right approach is to dive in and determine the cause and see what causes the issue; then fix. @baileypumfleet Thoughts?

**Comment by emrysal** [comment]
@baileypumfleet I already did a little dive into the the issue and the problem originates from Prisma: https://github.com/prisma/prisma/issues/6684

**Comment by bennetfabian** [comment]
> @baileypumfleet I already did a little dive into the the issue and the problem originates from Prisma: [prisma/prisma#6684](https://github.com/prisma/prisma/issues/6684)

> The fix will be in the release next Tuesday.
Maybe you or @baileypumfleet could keep an eye on new Prisma releases so you could update Prisma in Calendso if it really comes next Tuesday. 👍🏼

**Comment by bennetfabian** [comment]
> @bennetfabian My distribution unfortunatly does not support v16, but Prisma does seem to have already addressed this issue; I have created a branch @ [https://github.com/emrysal/calendso/tree/hotfix/node-v16-crash-%23174](https://github.com/emrysal/calendso/tree/hotfix/node-v16-crash-%23174?rgh-link-date=2021-05-07T21%3A59%3A50Z) .
> 
> Could you give that a shot and confirm that fixes your issue?
> 
> Edit: see [prisma/prisma@`2.22.0` (release)](https://github.com/prisma/prisma/releases/tag/2.22.0)

@emrysal It perfectly works using NodeJS v16.

P.S.:
```
prisma:warn Prisma "db push" was in Preview and is now Generally Available.
You can now remove the --preview-feature flag.
```

Maybe you could change README and remove that flag and then create a PR with both: the new package.json and the new README.
