### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by asharabu** [calendso/calendso#185]
Hi,
I have deployed calendso in my local environment and I created a test user via Prisma studio but getting authentication error while trying to login to calendso URL. Please note that I have tried by encrypted password on Prisma studio when creating the user also tried without encrypted one.
![image](https://user-images.githubusercontent.com/42669995/117796868-16491600-b26d-11eb-86f0-ba6dbd5ff454.png)

![image](https://user-images.githubusercontent.com/42669995/117796487-c23e3180-b26c-11eb-8cb9-63e351c87269.png)

Could you please let me know how to trouble shot this?

**Comment by emrysal** [comment]
Seen quite often is that the password encrypted text is added to prisma with an extra space, that's a good place to check.

**Comment by rberrelleza** [comment]
I just ran into the same issue. Bcrypt adds an extra space at the end when you copy the hash from there. I pasted it into an editor, removed the extra space, and then copy/pasted from there to prisma studio.
