### ISSUE TITLE
Internationalized and multilingual support

### ISSUE THREAD

**Issue by sijad** [calendso/calendso#19]
should be feasible by using https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by sharno** [comment]
There are a few options for actually adding i18n because nextjs doesn't come with a solution out of the box. I'd suggest 'next-translate' as an easy straightforward option.

**Comment by aminnairi** [comment]
I just happen to have written a tag-function-based i18n library that is super lightweight and I'm very happy with the API I come up with. There are many alternatives for React and Next but you can take a look if you want.

https://www.npmjs.com/package/@aminnairi/translation

I'll be happy to provide support anytime you need and I want it to be open-source as well as your project. Don't hesitate to open issues if you want to ask anything about it.

**Comment by rohitjmathew** [comment]
I had recently added i18n support for [readme.so](https://readme.so/) and had used [next-18next](https://github.com/isaachinman/next-i18next). Wouldn't mind supporting and helping on this project as well.

**Comment by PeerRich** [comment]
hey all. I've started a branch called `react-intl` where I've extracted a few keys already in `lang/en_EN.json` however @baileypumfleet decided to postpone implementation because it would slow Calendso down in shipping new features, especially since layouts & texts will change in the next few weeks.

if y'all want feel free to continue in this new branch but make sure to rebase a lot.

Intl is very important for us, but getting to "feature complete" has a slightly higher priority 🙏

**Comment by pret-a-porter** [comment]
Hey guys! What do you think about implement this feature by https://github.com/ibitcy/eo-locale? If maintainers are ok with it, I would happy to make PR

**Comment by s-gbz** [comment]
I'd like to help out with the german translation! :)

**Comment by Jan10** [comment]
> I'd like to help out with the german translation! :)

https://github.com/calendso/calendso/pull/133 :)

**Comment by s-gbz** [comment]
Awesome Jan! Are you good with it? Thanks a lot and feel free to hit me up if you'd like to share the weight.

**Comment by DariusLau** [comment]
Happy to help with Spanish :)

**Comment by hichnicksemen** [comment]
Ready to translate to Russian

**Comment by zomars** [comment]
Happy to contribute Spanish translations as well

**Comment by PeerRich** [comment]
can you join our slack? we have an #i18n channel and we'd love to have you

**Comment by ykguleriu** [comment]
> can you join our slack? https://calendso.com/slack we have an #i18n channel and we'd love to have you

More than happy to help with the Turkish translation! By the way is the #i18n channel closed?

**Comment by baileypumfleet** [comment]
We've since added i18n, please head to the #i18n channel on Slack if you wish to contribute!
