### ISSUE TITLE
Different colors for different event types

### ISSUE THREAD

**Issue by rberrelleza** [calendso/calendso#192]
> Please check if your Feature Request has not been already raised in the [Discussions Tab](https://github.com/calendso/calendso/discussions), as we would like to reduce duplicates. If it has been already raised, simply upvote it 🔼.

### Is your proposal related to a problem?

It would be nice if different colors had different event types (or even icons/emoji). this would make it easier to differentiate. Right now, they all have the same blue dot, which to me is confusing.

![image](https://user-images.githubusercontent.com/475313/117898820-ae013100-b27a-11eb-9656-c27187f2848f.png)

**Comment by jasmeetsohal** [comment]
@rberrelleza 
I did some experiment with random color generation and the expected output screen is somehow satisfying the need, have a look.
![image](https://user-images.githubusercontent.com/20149200/118025240-3962eb00-b37d-11eb-9fbc-eb598aa063bd.png)

**Comment by rberrelleza** [comment]
I like it very much! I think it gives a nice visual separation.

**Comment by jasmeetsohal** [comment]
@rberrelleza 
This pull request will close this issue :- https://github.com/calendso/calendso/pull/199

**Comment by jasmeetsohal** [comment]
@baileypumfleet  @rberrelleza 
The pull request was merged. Could you guys please close this open issue?
