### ISSUE TITLE
Available hours are not displayed when I select the  day

### ISSUE THREAD

**Issue by rberrelleza** [calendso/calendso#193]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Available hours are not displayed when I select the day. When I go to a day, the availability is shown briefly, it flashes, and then nothing is displayed.

### Steps to Reproduce
https://www.loom.com/share/c4c2ac650c8c4c99a4c85290ad46ae75

### Technical details
* Browser version: Chrome
* Node.js version: 14
* Built a container using the latest from the main branch

I don't see any errors on the browser or coming from node. where else can I look for issues?

**Comment by rberrelleza** [comment]
I'm seeing a response from the API, and in a few days I do get a time or two displayed. I wonder if the function that calculates the available time is getting confused?

**Comment by emrysal** [comment]
What are your start and endtimes like?

**Comment by rberrelleza** [comment]
This is my current config:
![image](https://user-images.githubusercontent.com/475313/118035584-41407200-b320-11eb-980d-e217ef24dedd.png)

**Comment by rberrelleza** [comment]
When I click on a date, the function that starts on https://github.com/calendso/calendso/blob/main/pages/%5Buser%5D/%5Btype%5D.tsx#L27 gets called 4 times. The first 3 times the value of the `times` variable is correct, but the 4th time it's always an empty array.  Maybe @baileypumfleet has some insight into what's going on here?

**Comment by baileypumfleet** [comment]
Could you share the output for the API calls from the 'Network' tab of your browser's developer console?

**Comment by rberrelleza** [comment]
The only output is this?

Request:
```
curl 'https://calendso.okteto.community/api/availability/ramiro?dateFrom=2021-05-20T07:00:00Z&dateTo=2021-05-21T06:59:59Z' \
  -H 'authority: calendso.okteto.community' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://calendso.okteto.community/ramiro/okteto' \
  -H 'accept-language: en-US,en;q=0.9,es;q=0.8' \
  -H 'cookie: __Secure-next-auth.callback-url=https%3A%2F%2Fcalendso.okteto.community; __Host-next-auth.csrf-token=0dacbb5f4cb4cdbb88aa80ee0db06453284a7f597bcdafff1f30c6797674b267%7C52b51a1bec6f4d8f64fd48e56b8ce06896d61001fedf31f7f3367c881f3257a5' \
  --compressed
```

Response:
```
[{"start":"2021-05-21T04:00:00Z","end":"2021-05-21T04:15:00Z"},{"start":"2021-05-20T15:00:00Z","end":"2021-05-20T16:30:00Z"},{"start":"2021-05-20T07:00:00Z","end":"2021-05-20T16:30:00Z"},{"start":"2021-05-20T17:15:00Z","end":"2021-05-20T17:45:00Z"},{"start":"2021-05-21T03:00:00Z","end":"2021-05-21T06:59:59Z"},{"start":"2021-05-20T07:00:00Z","end":"2021-05-20T08:45:00Z"},{"start":"2021-05-20T14:00:00Z","end":"2021-05-21T06:59:59Z"}]
```

**Comment by nitishsainani** [comment]
Here is the issue trace

`TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at eval (webpack-internal:///./lib/calendarClient.ts:229:171)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async handler (webpack-internal:///./pages/api/availability/[user].ts:22:24)
    at async apiResolver (/Users/nitishsainani/workspace/projects/temp/calendso/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/Users/nitishsainani/workspace/projects/temp/calendso/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/Users/nitishsainani/workspace/projects/temp/calendso/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/Users/nitishsainani/workspace/projects/temp/calendso/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/nitishsainani/workspace/projects/temp/calendso/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/Users/nitishsainani/workspace/projects/temp/calendso/node_modules/next/dist/next-server/server/next-server.js:32:504)`

**Comment by raro42** [comment]
May this be related to what I see in cometa E2E testing? 

The videos for that 
https://user-images.githubusercontent.com/29251049/120757208-88c9b080-c510-11eb-8b77-8f49e216d56e.mp4

All E2E tests are failing since 04.06. 01:00 UTC+2

**Comment by rberrelleza** [comment]
I think the issue might be related to running calendso on a subdomain. I see the same behavior when I see my public page via https://app.calendso.com/ramiro, while  https://calendso.com/ramiro works fine.

**Comment by maxonss** [comment]
I had the same issue and using a sub-domain as well, I tried deleting Google Calendar integration and linking it again and it seems to work

**Comment by Rrrricky** [comment]
I have the same issue on some random days. Deleting and linking the integration again (without using a subdomain) didn't help

**Comment by misterkanister** [comment]
I have the same issue on random days. Running on a subdomain as well.

**Comment by emrysal** [comment]
Is this still an issue for you guys after the reworked slot logic?
