### ISSUE TITLE
Prisma studio error

### ISSUE THREAD

**Issue by asharabu** [calendso/calendso#200]
Hi,

I could launch Prisma studio by executing the command `npx prisma studio` and able to access the URL with IP:5555 and able to see the screen correctly as shown below,
![image](https://user-images.githubusercontent.com/42669995/118360161-17977d00-b5a4-11eb-92a2-b374f31b7ac7.png)

But when we refresh the page it's not showing icons,
![image](https://user-images.githubusercontent.com/42669995/118360193-30a02e00-b5a4-11eb-8d55-2964a786612d.png)

I can see the below error on terminal

> 
/opt/app $ npx prisma studio
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'fields' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     ...
    |     index 0 -> object with constructor 'Object'
    --- property 'type' closes the circle
    at JSON.stringify (<anonymous>)
    at serialize (/opt/app/node_modules/prisma/build/index.js:131814:17)
    at HTTPNodeTransport.respond (/opt/app/node_modules/prisma/build/index.js:131829:34)
    at /opt/app/node_modules/prisma/build/index.js:140730:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

>

**Comment by baileypumfleet** [comment]
This is an issue with Prisma Studio itself and is not related to Calendso. I'll close this off, but any issues should be directed to Prisma themselves :)

**Comment by asharabu** [comment]
@baileypumfleet Is there any other way can we create users for calendso instead of using Prisma studio?
