### ISSUE TITLE
Loading spinner never stops and timeslots are blank

### ISSUE THREAD

**Issue by jimafisk** [calendso/calendso#202]
### Issue Summary

If you do not add at least one integration (https://app.calendso.com/integrations), when you view your calendar and click on a date, the loading spinning will just run continuously and never stop. 

<details>
<summary>Loading forever screenshot</summary>

![loading](https://user-images.githubusercontent.com/5913244/118408221-9ba83e00-b652-11eb-8417-37c306739634.png)

</details>

If you do not have "start and end times" set in your availability settings (https://app.calendso.com/availability), the timeslots will not show up after you select a day from the calendar picker.

<details>
<summary>Blank timeslots screenshot</summary>

![blank](https://user-images.githubusercontent.com/5913244/118408234-ac58b400-b652-11eb-86f8-b64f3dda1789.png)

</details>

### Steps to Reproduce
1. Add a new Event Type
2. Fail to set up an Integration or Availability settings
3. Click on "view" for that Event Type
4. Select a date and the timeslots will not be available

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I've discussed this with @baileypumfleet so we know what causes this issue, but thought it was worth documenting in case others run into the same issue and are confused. I also think there is an opportunity for this to fail more gracefully or prompt the user to fill out any information that is required for the app to work properly. 

### Technical details

Without the integration set up, the console will throw a 500 server error like this (in chrome):

```
[type]-1sf8420737cfd27fr89c.js:1 GET https://app.calendso.com/api/availability/yourapp?dateFrom=2021-05-17T04:00:00Z&dateTo=2021-05-18T03:59:59Z 500
```
and

```
Uncaught (in promise) SyntaxError: Unexpected token I in JSON at position 0
```

Without the availability settings configured, there is no console error.

**Comment by baileypumfleet** [comment]
Please see issue #201
