### ISSUE TITLE
Google Calendar integration is not created

### ISSUE THREAD

**Issue by alissonash** [calendso/calendso#207]
### Issue Summary
I'm not able to add a new integration. Apparently, all requirements are set correctly.

I get the OAuth Agreement Screen all right. However, I'm directed to the home screen of the application again. No mistake, nothing.

In this way, there is no addition of integration

### Steps to Reproduce
1. Add your first integration 
2. OAuth Agreement (OK)
3. Return home page, querie on link /?code=<hash/token>&scope=https://www.googleapis.com/auth/calendar.readonly%20https://www.googleapis.com/auth/calendar.events%20https://www.googleapis.com/auth/calendar

And it continues without any active integration!

### Technical details
* Browser version: https://www.whatsmybrowser.org/b/1UAJQ
* Node.js version: v14.17.0
* yarn run v1.22.10

**Comment by emrysal** [comment]
@alissonash And there is no output from the console? Nothing like "Error retrieving access token"?

**Comment by alissonash** [comment]
Tks for the reply @emrysal.

I realized through Chrome Developer Mode that a JWT token request is made, but none is used. The only token used is __Secure-next-auth.session-token

And I still don't get any errors! :/ 
Neither on the server console, nor in dev mode in Chrome.

Any tips on any procedure I can perform?

User configs:
id user: autogenerate
username: name
name: Name Lastname
email: name@domain.com
password: bcrypt-generator hash

**Comment by emrysal** [comment]
@alissonash Try figuring out what is going on by adding a `console.log(session)` inside the pages/api/integrations/googlecalendar/callback.ts file. There must be a session available as it would otherwise respond with "You must be logged in to do this".

It should look roughly like:
```javascript
{
  user: {
    name: 'your_name',
    email: 'your@email.com',
    image: '...',
    id: 1,
    username: 'username'
  },
  expires: '2021-06-23T13:59:31.834Z'
}
```

**Comment by alissonash** [comment]
@emrysal  In the `callback.ts` file nothing is returned using `console.log(session)`, however, adding this same output in the `add.ts` file I have this same output that informed me.

**Comment by alissonash** [comment]
I realized that the callback was not being called.

That way, when I added the integration and returned to the home page, I decided to change the URL and add the path with the callback.

from: `<calendso_url>/?code=<hash/token>&scope=https://www.googleapis.com/auth/calendar.readonly%20https://www.googleapis.com/auth/calendar.events%20https://www.googleapis.com/auth/calendar`

to:`<calendso_url>/api/integrations/googlecalendar/callback/?code=<hash/token>&scope=https://www.googleapis.com/auth/calendar.readonly%20https://www.googleapis.com/auth/calendar.events%20https://www.googleapis.com/auth/calendar`

This way it worked correctly, however, it needs to be analyzed as to why it is returning to the home, and not calling the callback url

**Comment by alissonash** [comment]
I entered my mistake.

In the Google API, it had two allowed URLs for targeting: `root` and `api/integrations/googlecalendar/callback`. Removing the root url returned to work, I believe that because of this code snippet in `add.ts`: `redirect_uris[0]`

```node
const oAuth2Client = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);
```

Thanks man @emrysal !

**Comment by raro42** [comment]
@alissonash @emrysal - Perfect that it worked out and was just a URL callback problem.  Thanks for closing.
