### ISSUE TITLE
disable day (gray) if no date available

### ISSUE THREAD

**Issue by PeerRich** [calendso/calendso#211]
### Is your proposal related to a problem?

users should not be able to click on a date, when no time is available

![image](https://user-images.githubusercontent.com/8019099/119173327-08f70d00-ba5f-11eb-8055-d320d4a55a6a.png)

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/8019099/119173501-3f348c80-ba5f-11eb-8207-753cd761c177.png)

(Describe your proposed solution here.)

disable dates, similar to dates of the past

**Comment by Kaeson** [comment]
I think this is similar as #162 ?

**Comment by PeerRich** [comment]
agree!
