### ISSUE TITLE
Issue with Email Notifications

### ISSUE THREAD

**Issue by jtylerhartley** [calendso/calendso#221]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
A summary of the issue. This needs to be a clear detailed-rich summary. 

### Steps to Reproduce
1. Open my bookings page
2. Book an appointment (the error then occurs)

<img width="1039" alt="Screen Shot 2021-05-28 at 12 49 10 PM" src="https://user-images.githubusercontent.com/70040274/120035353-502b5380-bfb3-11eb-839f-05be09b9cdff.png">

### Technical details
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
* Node.js version
* Anything else that you think could be an issue.

**Comment by emrysal** [comment]
@jtylerhartley This is going to be highly dependent on your setup - Gmail is a bit of a nightmare to deal with - I have had marginal success with:

```
EMAIL_SERVER_HOST='smtp.gmail.com'
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER='<user>@gmail.com'
EMAIL_SERVER_PASSWORD='If two factored - use APP password, if not, use user password.'
EMAIL_FROM='' // PS. due to limitations in Gmail, this does not get used. It will send from the authenticated account anyway and doesn't take into account the From: header. Make sure to create a separate account such as notifications@yourdomain.com to authenticate with.
```

Could you let me know if that is enough information to get your setup to work?

**Comment by jtylerhartley** [comment]
Yes, I got it working. Thank you!

**Comment by tacodicaprio** [comment]
Any plan on implementing XOAuth2 to avoid having to hardcode Gmail password?
