### ISSUE TITLE
Issue: Scheduling Appointments with no integrations

### ISSUE THREAD

**Issue by jtylerhartley** [calendso/calendso#222]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
A summary of the issue. This needs to be a clear detailed-rich summary. 

### Steps to Reproduce
1. Remove all integrations
2. Open the scheduling page
3. Schedule a meeting

Any other relevant information. 
<img width="1067" alt="Screen Shot 2021-05-28 at 12 24 23 PM" src="https://user-images.githubusercontent.com/70040274/120035614-be701600-bfb3-11eb-910d-a2919992cd8e.png">

### Technical details
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
* Node.js version
* Anything else that you think could be an issue.

**Comment by jtylerhartley** [comment]
I just reproduced the error with this log. The date is **?date=2021-05-29T15:00:00Z&type=3**
<img width="1053" alt="Screen Shot 2021-05-28 at 3 25 22 PM" src="https://user-images.githubusercontent.com/70040274/120047266-08afc200-bfc9-11eb-8471-39a192e23a4a.png">

**Comment by emrysal** [comment]
Thank you! Reproduced and preparing PR now.
