### ISSUE TITLE
iframeResizer.js:12 Failed to execute 'postMessage' // hours do not show

### ISSUE THREAD

**Issue by raro42** [calendso/calendso#227]
### Issue Summary
E2E testing on calendso.com "try-demo" fails to load hours available with an error message in console

``` 
iframeResizer.js:12 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://platform.shoutout.so') does not match the recipient window's origin ('https://calendso.com').

Uncaught TypeError: Cannot read property 'replaceChild' of null
    at buttons.js:6
    at buttons.js:6
    at buttons.js:6
    at buttons.js:6
    at buttons.js:6
    at XMLHttpRequest.<anonymous> (buttons.js:6)
```

### Steps to Reproduce
1. goto https://calensdo.com/
2. Clicked on "Try live-demo"
3. Select next month
4. Select first available day
5. Shows spinner
6. Ends up in blank page and error msg in console

Expected:
* see available hours

### Technical details
E2E testing started 24.5. 14:00 UTC+2 and runs scheduled every hour. We have sporadically seen results as described above once or twice a day. 

Since 28.5. 8:00 UTC+2 we sporadically see successfull tests and generally see above behaviour.

Today we could reproduce the behaviour manually.

* Browser version: Chrome 88, Chrome 90, Edge 90, Firefox 88 on Windows 10
* see video and screenshot on slack discussion channel

**Comment by baileypumfleet** [comment]
I can't seem to reproduce this issue, I selected next month (1st July) and it took a while, but it works

**Comment by raro42** [comment]
Reviewed the cometa logs. 

Tests are green since 1.06. 17:00 UTC+2.

Will close this issue. The error has gone away for the past two days. It might have been a problem in the underlying infrastructure.
