### ISSUE TITLE
Booking confirmed add to calendar 'refused to connect' when in iframe

### ISSUE THREAD

**Issue by ldoherty74** [calendso/calendso#235]
When adding the calendar to a website using the iframe the add to calendar function in the booking confirmation does not work, it shows a 'refused to connect' calendar error. If the calendar link is opened in a new tab, then it works OK. How does one update the code to add target="_blank"> to the calendar icons?

**Comment by baileypumfleet** [comment]
Could you please provide a screenshot of this error please?

**Comment by ldoherty74** [comment]
Thank you for getting back to me. Here is a screencast of the issue :)

**Comment by baileypumfleet** [comment]
Apologies, @ldoherty74 , but I can't see any screen cast attached or linked there

**Comment by ldoherty74** [comment]
I have attached a screencast to this email. Here is a link to the
screencast also https://nimb.ws/C4vo3e

**Comment by baileypumfleet** [comment]
Are you still experiencing this? We've changed a lot since then
