### ISSUE TITLE
Calendar layout (day alignment is incorrect)

### ISSUE THREAD

**Issue by jimafisk** [calendso/calendso#24]
First of all, thanks for open sourcing this project! Congrats on the launch, the product looks really great and I'm excited to use it!

There's an issue with the alignment of the days on the calendar when I take a look at the demo (https://app.calendso.com/bailey/1). It looks like the first day of the month starts in the top left of the month view, regardless of which day of the week the first day of the month actually is. That causes all the following days to be misaligned, so clicking on the 23rd of April for example is a Friday, but it's spatially in the column that would typically be a Monday on most calendars. 

This is summed up in a comment on hacker News (https://news.ycombinator.com/item?id=26818957):

> Also, what an odd calendar layout. Starting with the first day of the month at the top left means all the days are off for most months. Why would Thursday be at the very left side (as is the case in April)?? (I was initially trying to find out if the layout was Sunday or Monday starting, but apparently it's neither)

<details>
<summary>Demo Screenshot</summary>

![april](https://user-images.githubusercontent.com/5913244/114927022-04f02380-9dff-11eb-9a41-bd33b0d797ef.png)

</details>

<details>
<summary>Correct layout for April 2021 Screenshot</summary>

![april2](https://user-images.githubusercontent.com/5913244/114927062-10434f00-9dff-11eb-95e2-cdcfedddbc3c.png)

</details>

**Comment by PeerRich** [comment]
absolutely. this is one of the next mini-updates, @baileypumfleet and I didn't found time before the release deadline to ship this

**Comment by baileypumfleet** [comment]
Fixed, thanks to @hedwardd :)
