### ISSUE TITLE
It's possible to book events even when availability forbids it

### ISSUE THREAD

**Issue by Nico-J** [calendso/calendso#244]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
The system allows me to book events at time slots that aren't available at all. Not only that I can book slots outside my availability window, I can also book slots even when there are other appointments in my calendar at that time. The reason is a lack of user-delivered payload data verification in the backend, not the frontend.

### Steps to Reproduce
1. Go to the event owner page and select a day.
2. As expected, it only shows the time slots that are still available. Choose any slot you want:
![image](https://user-images.githubusercontent.com/14024119/120981463-faeffe80-c777-11eb-939a-07600c75bb6a.png)
2. It brings you to the form to fill in information about you. Instead of filling this in, change the date and time in current URL to your desired appointment date. For example from:
`https://<yourdomain>/Nico/book?date=2021-06-07T11:30:00Z&type=2` to `https://<yourdomain>/Nico/book?date=2021-06-08T04:30:00Z&type=2`
3. Meanwhile, my available time is configured from 12pm to 1pm:
![image](https://user-images.githubusercontent.com/14024119/120982297-d7798380-c778-11eb-9723-11bbd3917b95.png)
Also, I've scheduled a very important personal appointment in my calendar at the time given in the url:
![image](https://user-images.githubusercontent.com/14024119/120982414-fc6df680-c778-11eb-8262-8bcd058f3ed3.png)
4. Nevertheless, it offers me to book the event:
![image](https://user-images.githubusercontent.com/14024119/120982494-0ee83000-c779-11eb-9d81-a75681f21575.png)
5. When I fill in the data and book it, it actually works and I got an appointment:
![image](https://user-images.githubusercontent.com/14024119/120982662-3939ed80-c779-11eb-8f18-58f88b5178ec.png)

This shouldn't be possible. Never trust the user, so I'd expect the backend to check the availability again when receiving the user data. Otherwise, one could easily gather appointments that should never be available and even try to outdo other clients when free slots are rare.

### Technical details
* Browser version: Chrome 90, Ubuntu 20.04
* Node.js version: 12.16.2

**Comment by jimafisk** [comment]
We're having the same issue across multiple calendars under different Calendso accounts. This is causing lots of double booking problems. 

<details>
<summary>Screenshot of integrated Google Calendar</summary>

![gcal](https://user-images.githubusercontent.com/5913244/123290386-3a8c4980-d4df-11eb-9cf3-44c83616c0f8.png)


</details>

<details>
<summary>Screenshot of Calendso</summary>

![calendso](https://user-images.githubusercontent.com/5913244/123290398-3e1fd080-d4df-11eb-94a2-4142c341c101.png)


</details>

**Comment by femyeda** [comment]
Committing a fix for this later today.

**Comment by masteradit** [comment]
Hey @femyeda! I am facing a similar issue. Even if there is an event in my Google calendar, when a user opens my Calendso page, it shows that slot as available.

**Comment by olliepalmer** [comment]
I'm having similar issues - in my case I can book the same time slot again and again. It's like it isn't checking my calendar at all, just writing to it.

Here are two events I was able to book at the same time:

![Screenshot of two events](https://www.dropbox.com/s/tctqdomic623ajv/Screen%20Shot%202021-09-10%20at%2011.31.22.png?dl=1)
