### ISSUE TITLE
select calendar on google account

### ISSUE THREAD

**Issue by Freundschaft** [calendso/calendso#259]
right now, it seems like availability is checked against all calendars that are visible on a google account.
also events are always created on the primary account.
users should be able to select which calendar they want to use for each of these actions

**Comment by chrispruitt** [comment]
I would like to add something to this suggested feature. It would be nice if we could, optionally, modify the event details for a selected calendar before creating the calendar event. Say for instance, we want an event to be created on our primary calendar, but then we just want to block that time out on another calendar with and event titled "BLOCK TIME" and no description.

**Comment by ConnorGargano** [comment]
Hi @Freundschaft
Thank you for bringing this to our attention.
Sorry for the delayed response, this is now possible and if you need assistance in selecting calendars from your Google account, please refer to our step by step documentation here 👉 https://docs.calendso.com/docs/selecting-calendars#selecting-specific-calendars
