### ISSUE TITLE
Iframe Embed shows wrong URL

### ISSUE THREAD

**Issue by SimonMayerhofer** [calendso/calendso#264]
### Issue Summary
The iframe embed text shows 
```<iframe src="https://calendso.com/simon" frameborder="0" allowfullscreen></iframe>```
but should show the link set with `BASE_URL`.
This applies to both `Standard iframe` and `Responsive full screen iframe`

**Comment by PeerRich** [comment]
@baileypumfleet easy quick fix

**Comment by baileypumfleet** [comment]
Fixed
