### ISSUE TITLE
Star count

### ISSUE THREAD

**Issue by bl-ue** [calendso/calendso#27]
Hello!

This looks like a nice and promising project.  I'm glad to have found out about it.

However, I'm more than a bit perplexed at the fact that yesterday (https://star-history.t9t.io/#calendso/calendso) it had 30 stars, and at the time I'm writing this (01:00 UTC Apr 16) there's 975 stars.  About every 1 minute, when I reload the page, I see it has another star 🤔 

Any reason for this?

**Comment by 50bbx** [comment]
Hi @bl-ue,

This is because the maintainers of the repo [launched on Product Hunt](https://www.producthunt.com/posts/calendso).

**Comment by bl-ue** [comment]
Really? That's all?  There's no SEO injection or anything like that?

**Comment by baileypumfleet** [comment]
No, simply just a launch on Product Hunt and Hacker News.

**Comment by bl-ue** [comment]
Well then, wow. Great job developing a product that's already popular and definitely full of potential!! 🥇
