### ISSUE TITLE
Event's month is incorrect in Gmail

### ISSUE THREAD

**Issue by Eric-SDS** [calendso/calendso#280]
### Issue Summary
When receiving a new event via email, the mail subject shows the correct date, however gmail's suggestion for the calendar event is off by one month

### Steps to Reproduce
1. Schedule a meeting
2. Open the email Calendso sends you in Gmail.
3. Notice that inside the email Gmail's suggestion for google calendar is off by one month.

**Comment by emrysal** [comment]
Hi @Eric-SDS

This was fixed in https://github.com/calendso/calendso/pull/268 which seems to have been merged in around the same time this issue was opened, it is fixed in main.

Alex
