### ISSUE TITLE
Cancel page not working? Cannot read property 'length' of null

### ISSUE THREAD

**Issue by garethvanzyl** [calendso/calendso#281]
**Issue Summary**

After choosing a calendar booking slot, and having it saved to one's own Gmail calendar, the cancel link doesn't seem to work properly after clicking it. When clicking this link, I get the following error: "TypeError: Cannot read property 'length' of null". This error is thrown on line 106 of 'pages/cancel/[uid].tsx where the line has the following code: {props.eventType.length} minutes

### Steps to Reproduce
1. Created an event, entered the detail, time length etc (filled in every field)
2. Shared a link with a user.
3. The user then chose a time, scheduled it.
4. Then, upon trying to click on the cancel link, which is inside the user's Gmail calendar now, the link brought up the error described above.

### Technical details
* Latest Chrome Browser
* Node.js version 12.16.2

**Comment by Nico-J** [comment]
Hi @garethvanzyl ,
Thank you very much for your issue. I created a bugfix that should fix your problem. As soon as this issue is resolve, the fix will be available in the main repository.

Best regards,
Nico

**Comment by jtylerhartley** [comment]
@Nico-J This issue is still occurring for me. It seems as if someone has reverted your PR.
