### ISSUE TITLE
Support for automatic Google Meet link

### ISSUE THREAD

**Issue by 50bbx** [calendso/calendso#29]
Hey guys,

I have everything ready to add support for automatically generate a Google Meet link when creating an event. This is done on a per-event basis with a new column on the EventType table.

There are some nuances, but the main part is this, in the `pages/api/book/[user].ts` when creating the event:

```js
{
  // ...
  conferenceData: {
    createRequest: {
      requestId: Math.random().toString(36).substring(7), // just generating any random string should do the trick
      conferenceSolutionKey: {
        type: "hangoutsMeet"
      },
    }
  }
}
```

If this is something you are interested in, I will do a PR.

**Comment by rittmang** [comment]
Was waiting for this, to be honest =D

**Comment by carl0s** [comment]
wow please me to!

**Comment by MaZderMind** [comment]
See #102 for a draft implementation
