### ISSUE TITLE
Layout on mobile vs desktop

### ISSUE THREAD

**Issue by rittmang** [calendso/calendso#30]
## Mobile view (small widths)
![image](https://user-images.githubusercontent.com/28761428/114973091-56e78680-9e9d-11eb-9e56-77b2c77f9f27.png)

Some buttons like Teams and Bookings are visible. And none of the tab links work, since I guess the hrefs are not specified.

## Desktop view (larger widths)
![image](https://user-images.githubusercontent.com/28761428/114973154-80081700-9e9d-11eb-8b13-a49b53cae91f.png)

Teams and Bookings tab buttons are invisible and links work, which is the intended behaviour I believe at the moment?

**Comment by baileypumfleet** [comment]
Yes, the Shell component needs to be updated with the correct links for this. Also, it is correct that the Teams and Bookings should be disabled.

**Comment by baileypumfleet** [comment]
Issue has been fixed in the latest commit 😄

**Comment by rittmang** [comment]
Great, thanks!
