### ISSUE TITLE
Demo not loading slots

### ISSUE THREAD

**Issue by alderson59** [calendso/calendso#317]
Just found this fantastic project - Came over here from monitoring this issue from another repo https://github.com/alextselegidis/easyappointments/issues/209 for almost a year now. Solve this pain point and Calendso is set to be the standard for appointments for many self-hosted users coming from Nextcloud et al.

Anyway, back to the issue: I was trying out calendso.

### Issue Summary
A summary of the issue. This needs to be a clear detailed-rich summary. 
https://calendso.com/rick/quick-chat:
![image](https://user-images.githubusercontent.com/69715968/123635873-c4754300-d84e-11eb-9525-136460fbe9af.png)

https://calendso.com/
![image](https://user-images.githubusercontent.com/69715968/123635922-d3f48c00-d84e-11eb-9a23-99b35f913b2d.png)
Loads forever

Rick Astley seems to be shutting out appointments these days 😂

### Technical details
* Browser version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

**Comment by PeerRich** [comment]
thank you for the kind words 😍 we intend to become the open standard for anything booking and the love of the community is amazing to see.

agree, rick has been very busy--something broke the demo. we'll fix today 🙏

**Comment by alderson59** [comment]
@PeerRich Thanks for the reply - Not long after I posted the comment above, I went and looked for docker support and ran into calendso's most commented upon issue: https://github.com/calendso/calendso/pull/7 

I made a comment in that issue and am wondering why Calendso is taking such a stance? :/

**Comment by PeerRich** [comment]
we don't have any docker experts on the team yet so we don't feel comfortable offering "official" support yet. 

it is coming at some point tho.
