### ISSUE TITLE
Cancellation and rescheduling links

### ISSUE THREAD

**Issue by baileypumfleet** [calendso/calendso#33]
We need to add a section at the bottom of the calendar event descriptions allowing people to cancel and reschedule their meetings.

Like so:
> **Need to change this event?**
> Cancel: https://calendso.com/cancel/1289347189247
> Reschedule: https://calendso.com/reschedule/1289347189247

**Comment by baileypumfleet** [comment]
A precursor to this is actually storing bookings in the database, in such a way that they can be referenced later to cancel or reschedule through the calendar APIs.

**Comment by Eisa01** [comment]
Is there currently no way to cancel (free a slot) ? or am I missing something?
I have tried deleting the event from the requester calendar, while it sends a notification that it has been declined; it does not free the slot in calendso .

Is there any current workarounds that are possible to free a slot in our self-hosted Calendso?

**Comment by baileypumfleet** [comment]
Deleting the event from the host's calendar will free it up in Calendso @Eisa01 . This issue is tracking having an automated link for the attendee to cancel the link through.
