### ISSUE TITLE
Calender showing busy when other user's calender is busy.

### ISSUE THREAD

**Issue by kartikye** [calendso/calendso#334]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
There are two accounts, me and my co-founder. My account is synced with my calendars and his with his. When i add an event to my calendar, it changes his calendso availability.

### Steps to Reproduce
1. Followed installation instructions
2. Created two accounts
3. Both logged in with our relevant google accounts
4. I blocked of an entire day on my calendar
5. Both of our availabilities changed.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: Firefox
* Node.js version
* Anything else that you think could be an issue.

**Comment by baileypumfleet** [comment]
You need to select which calendars you want to check for availability from in the Integrations page :)

**Comment by kartikye** [comment]
Neither of has the other person's calendar selected on the integrations page.

**Comment by baileypumfleet** [comment]
Sometimes it's calendar sharing rules that cause this to happen. Can you also confirm that you're on the latest codebase?
