### ISSUE TITLE
Issue with Zoom Link & Emails

### ISSUE THREAD

**Issue by jtylerhartley** [calendso/calendso#336]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
A summary of the issue. This needs to be a clear detailed-rich summary. 

I receive 2 confirmation emails - one with the Zoom link in it, and the other without it. Even if the event type doesn't have Zoom as an option. This is an issue because the invitee should not be invited to a zoom meeting if they want to schedule a in person event or google meet for example. 

### Steps to Reproduce
1. Book an event from the bookings page
2. The inviter and invitee both receive 2 emails, one with and one without a Zoom Link.

**Comment by baileypumfleet** [comment]
This is being worked on, and I believe we have a PR that is in review to fix this
