### ISSUE TITLE
The slots available for booking do not show up in order in the event url

### ISSUE THREAD

**Issue by ronykris** [calendso/calendso#337]
### Issue Summary
The slots available for bookings do not show up in order in the event url

### Steps to Reproduce
1. Create an event type
2. Edit event type.
3. Under "How do you want to offer your availability for this event type?" I created few slots of 20mins each
eg: 08:00 to 08:20, 08:30 to 08:50, 16:00 to 16:20 and 16:30 to 16:50
4. Update the changes.
5. You'll notice in the event url the slots do not show up in order of the time.
6. I also noticed that the order of the slots got re-arranged to a random order in the event edit page.

Attached are screenshots of the calendar in the event url showing weird order of slots.

<img width="576" alt="slotsNotInOrder" src="https://user-images.githubusercontent.com/20333193/124343954-2b974c80-dbed-11eb-8ab3-a1679cd48657.png">

<img width="576" alt="slotsNotInOrder-1" src="https://user-images.githubusercontent.com/20333193/124344018-9ba5d280-dbed-11eb-9b03-70b783b54820.png">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
I don't think this is browser specific. However, i have seen this pretty much on all the known browsers

**Comment by emrysal** [comment]
PR'ed a fix, the list was showing up in order in which they were entered in the database, but if you add multiple simultaneously those calls are happening async so may appear out of order. Fix is to order the availability by startTime.
