### ISSUE TITLE
Deploy on Railway seems to be broken

### ISSUE THREAD

**Issue by aktech** [calendso/calendso#340]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
The deploy to railway seems to be broken, the button [here](https://github.com/calendso/calendso#deployment)

### Steps to Reproduce
1. Click on the Deploy on Railway button.

<img width="273" alt="Screenshot 2021-07-04 at 13 15 14" src="https://user-images.githubusercontent.com/5647941/124384589-f0b71680-dcc9-11eb-9ff2-4a4c87108453.png">

Error:

<img width="854" alt="Screenshot 2021-07-04 at 13 13 39" src="https://user-images.githubusercontent.com/5647941/124384597-f90f5180-dcc9-11eb-8c5e-600f5e622d2b.png">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
* Node.js version
* Anything else that you think could be an issue.

**Comment by emrysal** [comment]
It looks like Railway had an issue connecting to Github (as the repo mentioned is the right repo). Added a video to show the behaviour - @aktech is this now fixed?

https://user-images.githubusercontent.com/1046695/124386758-c9fddd80-dcd3-11eb-863a-754c33e380d8.mp4

**Comment by aktech** [comment]
Seems to work now, thanks!
