### ISSUE TITLE
Error when attempting to book a slot

### ISSUE THREAD

**Issue by kndri** [calendso/calendso#342]
### Issue Summary
When attempting to book a slot, slots are not able to load as an error occurs.
"TypeError: Cannot read property 'every' of undefined"

When checking for scheduling conflicts within the function `handleAvailableSlots` is where the error occurs. Commenting out the loop for busyTimes causes slots to become avabile.
![Screen Shot 2021-07-05 at 2 13 25 PM](https://user-images.githubusercontent.com/56895441/124507149-3099fe80-dd9b-11eb-997e-0ad9096f138e.png)

### Steps to Reproduce
1. Went to an event page
2. Clicked on an available date

### Technical details
* Browser version: Chrome 91
* Node.js version: v14.17.1
* Anything else that you think could be an issue.

**Comment by emrysal** [comment]
Hi @kndri, do you have any integrations configured?

**Comment by kndri** [comment]
I do. I have Google Calendar configured.

**Comment by kndri** [comment]
But I see @femyeda has a PR for it in #331, might cherry-pick and see if that fixes the issues.

**Comment by emrysal** [comment]
@kndri Could you have a look at what the value of busyTimes is in your case? Normally; this must always be an array.

**Comment by kndri** [comment]
@emrysal it is undefined as nothing is being passed in `handleAvailableSlots` function.

![Screen Shot 2021-07-05 at 2 26 34 PM](https://user-images.githubusercontent.com/56895441/124508022-09443100-dd9d-11eb-8fe3-7190d5532561.png)

**Comment by emrysal** [comment]
This looks to be the issue; in main this looks like: 

https://github.com/calendso/calendso/blob/90d6f8faee015a6027fd326b175f5df15551cf3b/components/booking/Slots.tsx#L29-L40

**Comment by kndri** [comment]
yup that was it. Thanks!
