### ISSUE TITLE
start and end times skewed

### ISSUE THREAD

**Issue by florianoverkamp** [calendso/calendso#35]
Hi guys, 

great work with this first public version, off to a great start. 

In my playing around with this I noticed odd behaviour with the start/end times: When setting start and end times to (for instance) 09:00-17:00 this results in guests being able to plan from 9:15 (or similar, depending on chosen event duration) till 17:00. Expected behaviour would be being able to plan from 9:00 till 16:45. 

I think this should be a simple comparison bug somewhere (< vs <= or similar) but I'm still starting to find my way around this codebase, so I thought I'd report it here.

**Comment by emrysal** [comment]
Hi @florianoverkamp This is being addressed as part of #28

**Comment by baileypumfleet** [comment]
PR #28 has been added, so this issue should be resolved now.
