### ISSUE TITLE
Collective scheduling?

### ISSUE THREAD

**Issue by krlmlr** [calendso/calendso#357]
### Is your proposal related to a problem?

I'd like to be able to set up a meeting with me, one or two teammates, and an external party. I'd like the external party to be able to book the slots where *all* of my teammates (including myself) are available.

### Describe the solution you'd like

A link that I can share that opens the scheduling page for multiple persons.

### Describe alternatives you've considered

It looks like Harmonizely supports this to some extent: https://help.harmonizely.com/article/183-how-to-show-availability-when-all-teammates-are-available. Calendly seems to be one of the few that advertise this feature: https://help.calendly.com/hc/en-us/articles/223145867-Multi-person-scheduling-options-for-teams#2 . I'm not aware of other solutions.

### Additional context

Currently evaluating self-hosted calendso.

CC @pat-s.

**Comment by emrysal** [comment]
This is in the final stages of development and utilises the Team functionality that already exists within Calendso. I'll provide updates when the status changes.

**Comment by manuelbiermann** [comment]
I would like to add to this the following logic:

Show slots available where at least one of the team members is available and if more than one is available then allocate booking with round robin.

When is this useful?

I would like to have a booking link for my sales team which is in multiple timezones. This way we can give all leads one booking link to pick their most convenient time...

**Comment by baileypumfleet** [comment]
This was added a few weeks ago :)
