### ISSUE TITLE
People in non-ET timezones can pick invalid times

### ISSUE THREAD

**Issue by ColinChartier** [calendso/calendso#362]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
People in non-ET timezones can pick invalid times

### Steps to Reproduce
1. Create an event, make it available 10am - 6pm ET
2. Run TZ=UTC firefox 
3. Go to the appointment booking page, notice that slots for 10am UTC are available

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
* Node.js version
* Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
hey Colin, I made a ticket for the engineering team!

**Comment by kevintyj** [comment]
Just noticed the same issue :)

**Comment by baileypumfleet** [comment]
Apologies for the late reply, but this should have been fixed ages ago
