### ISSUE TITLE
request: video tutorial setup install

### ISSUE THREAD

**Issue by grand-lotus-iroh** [calendso/calendso#37]
congrats on product hunt achievement! i think it would be cool if you did a basic / simple self-hosted video tutorial on installing Calendso... perhaps using [Laragon](https://laragon.org/) or something.

good luck!

**Comment by baileypumfleet** [comment]
Somebody made a video on YouTube setting up Calendso. This isn't high enough priority for us to make ourselves, but if someone else wants to, then they're more than welcome :)
