### ISSUE TITLE
Cannot deploy to Railway

### ISSUE THREAD

**Issue by christianto88** [calendso/calendso#377]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I am unable to deploy calendso to railway. It always failed on build phase. The error indicate that it couldn't resolve dependency. I am using yarn

Updates : It worked by deleting yarn.lock and using package.lock.json instead

### Steps to Reproduce
1. Clicked Railway button to deploy

**Comment by baileypumfleet** [comment]
Unfortunately we cannot help with Railway, as we don't have any control over this. You should direct this to Railway's support and see if they can help
