### ISSUE TITLE
Feature suggestion: CalDav support

### ISSUE THREAD

**Issue by bennetfabian** [calendso/calendso#38]
Alongside Google & Office 365 calendar support maybe you could implement CalDav support as it's a nicely standardized, specified ([RFC4791](https://tools.ietf.org/html/rfc4791)) and widely used protocol in stacks which try to rely on "Big Tech" as little as needed.

**Comment by bennetfabian** [comment]
Oops just saw it already has a feature [voting link](https://feedback.calendso.com/posts/9/caldav-support) 😬

**Comment by ConnorGargano** [comment]
@bennetfabian 
Just an update for you! The engineering team have been working hard and I can now confirm that the CalDav integration has been added to Calendso 😁
