### ISSUE TITLE
2 Factor Authentication Support

### ISSUE THREAD

**Issue by bennetfabian** [calendso/calendso#39]
Guess the title should be self explainatory. 2FA via TOTP is a open standard which should normally be relatively easy to implement and is getting more important in this modern and connected time.

Corresponding feature voting in GitHub discussions: #72

**Comment by mffap** [comment]
Maybe you might want to consider a pattern where the user can choose the auth provider (hosted/managed OpenID Connect provider) but can define whether to require 2FA from your app via claims.
Full disclosure: I work for a company that develops an open-source IAM platform. I was interested in Calendso for personal reasons.

**Comment by shonfeder** [comment]
Just to note: the feature voting link is giving me a 404.

Since I'm already writing here, I may as well report that we are evaluating calendso for our use, and this one of the principle shortcomings so far.

**Comment by bennetfabian** [comment]
> Just to note: the feature voting link is giving me a 404.
> 
> Since I'm already writing here, I may as well report that we are evaluating calendso for our use, and this one of the principle shortcomings so far.

Dear @shonfeder,
the feature voting site has been moved to GitHub discussions on here. The new link for voting for 2fa would be #72.

**Comment by ConnorGargano** [comment]
Hi @bennetfabian,
We now support Two-Factor Authentication!
How to enable this can be found here: https://docs.cal.com/docs/settings/two-factor-authentication
-Thanks Connor
