### ISSUE TITLE
Custom Input (checkbox) incorrectly saves False value as True in dB

### ISSUE THREAD

**Issue by nsomaru** [calendso/calendso#398]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Checkbox custom input is saving "Yes" to description field although the checkbox is not ticked.

### Steps to Reproduce
1. Create an event with a checkbox custom input
2. Book the event without checking the checkbox
3. Inspect the contents of the `Booking.description` field in the db. The label of the field is saved, followed by _Yes_ finally followed by the comments you entered into the booking, if any

_Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?_

Since the field was unchecked, the value should be _No_ unless it was checked

### Technical details
* _Anything else that you think could be an issue_.

If we are using one dB column to save custom input fields, can we use a definite separator to parse out the fields? I created a simple webhook/notification system using Postgres LISTEN/NOTIFY and [n8n](https://n8n.io) and this would be extremely useful.

Thanks!

**Comment by Malte-D** [comment]
I will check that
