### ISSUE TITLE
Unable to login if running on custom port

### ISSUE THREAD

**Issue by pcrosthwaite** [calendso/calendso#4]
Currently the default port for nextjs is 3000. If a process is currently using this port, yarn dev will not work.

This can be corrected with `yarn dev -p 3030` but the callback etc. will fail when trying to login as it is expecting port 3000.

**Comment by mfts** [comment]
I had the same experience and actually got a hint from next-auth to add NEXTAUTH_URL to .env. I just made this quick PR for simplicity sake: #25

**Comment by baileypumfleet** [comment]
Should be resolved now with the latest PR being merged. Essentially, just set the NEXTAUTH_URL environment variable like @mfts mentions above and all should be good. I'll close this off for now, but if this issue continues, let me know.
