### ISSUE TITLE
Switch between 12 and 24 hour times

### ISSUE THREAD

**Issue by bennetfabian** [calendso/calendso#40]
Maybe you could implement the option to switch from 12hr time format to 24hr time format. 24hr time format is used almost everywhere at least in Germany, the rest of Europe and I think also many other parts of the world.

Corresponding [feature voting link](https://feedback.calendso.com/posts/18/24hr-time-format-option)

**Comment by baileypumfleet** [comment]
This is added in the latest commit. When you go to the booking page, there will be a timezone button on the left, which when expanded, allows you to switch between 12 and 24 hours.

![Screenshot 2021-04-20 at 15.42.42.png](https://images.zenhubusercontent.com/607d4743d9b19be844e7320d/0dc82279-2018-4815-b121-1efb38e84c3b)

**Comment by bennetfabian** [comment]
@baileypumfleet Very nice, thank you :)

> This is added in the latest commit. When you go to the booking page, there will be a timezone button on the left, which when expanded, allows you to switch between 12 and 24 hours.
> 
> ![Screenshot 2021-04-20 at 15.42.42.png](https://camo.githubusercontent.com/c15fc1bf4f6c1537950ec6830522fb67f586324852aaaa7c4db2b121415810d0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630376434373433643962313962653834346537333230642f30646338323237392d323031382d343831352d623132312d316566623338653834633362)

**Comment by msbt** [comment]
> This is added in the latest commit. When you go to the booking page, there will be a timezone button on the left, which when expanded, allows you to switch between 12 and 24 hours.
> 
> ![Screenshot 2021-04-20 at 15.42.42.png](https://camo.githubusercontent.com/c15fc1bf4f6c1537950ec6830522fb67f586324852aaaa7c4db2b121415810d0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630376434373433643962313962653834346537333230642f30646338323237392d323031382d343831352d623132312d316566623338653834633362)

Thanks for adding this, however, is it possible to make this a .env setting so it can be set to 24 hours by default or is there already a way to do that? Couldn't find anything in the ui-settings.
