### ISSUE TITLE
Postgres TIMESTAMP fields

### ISSUE THREAD

**Issue by nsomaru** [calendso/calendso#405]
### Issue Summary
The accepted wisdom in [the Postgresql wiki](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_timestamp_.28without_time_zone.29) is to prefer `TIMESTAMPTZ` type over the `TIMESTAMP` type for datetime fields.

I've been mucking around with the dB and noticed we're using `TIMESTAMP` on, for example "Booking"."startTime". I thought it worth mentioning here since that may be a config switch in the ORM we're using, but it could mean our date/time handling could be impaired in the future. Doubtless the migration will be easier to manage whilst still alpha.

Just a heads up, feel free to close if irrelevant.

Edit: Didn't seem worth opening a whole nother issue for this, but the ORM enforces case sensitivity on the fields its created which means you need to quote everything in Postgres if you're writing manual queries, which is...well, painful:

- "Booking"."startTime"
-  "Attendee"."bookingId"
-  ...etc

Postgres defaults to "everything lowercase" but those fields were obvious quoted when they were created. If there's a switch you can flip for that too, it might be useful for developer UX.

**Comment by emrysal** [comment]
Hi @nsomaru - I too think that the requirement for quotes is a bit painful but it is hard to undo some of the decisions made in the past re. naming of databases. There's a wipe needed there.

Currently our code handles the switch on `TIMESTAMP` and time based logic, in the future we will however start looking towards `TIMESTAMPTZ` for handling some of that logic.
