### ISSUE TITLE
Feature suggestion: ics file download at booking success page

### ISSUE THREAD

**Issue by bennetfabian** [calendso/calendso#41]
There could be a fourth button for downloading a ics file for the scheduled meeting. iCalender is standardized by RFC, has pretty good [documentation](https://icalendar.org/) and is universally usable. For example when you open such a file in macOS it starts your Calendar app and gives you the possibility to add it to one of your calendars you have configured. (for example Google, Yahoo, Outlook, CalDav, iCloud, etc)

There are several NodeJS libraries for generating ics files. Download could be done using [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

Corresponding [feature voting link](https://feedback.calendso.com/posts/19/ics-file-download-at-booking-success-page)

![image](https://user-images.githubusercontent.com/41294690/115101128-01b18080-9f42-11eb-821d-7316bde012f0.png)

**Comment by emrysal** [comment]
Thought this was a cool suggestion, implemented in #45
