### ISSUE TITLE
username changes are not reflected in the session object, breaking scheduling links & displaying the wrong username to the user

### ISSUE THREAD

**Issue by joshsny** [calendso/calendso#422]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
The username is stored and retrieved from the NextAuth session object, however in the settings page a user can change their username during the session. The new username will not show to the user, and any scheduling links will be broken as they will use the old username stored in the NextAuth session object. We can solve this by either:

1. Updating the session object mid-session, is this possible?
2. Retrieving the username from the database every time we need to

### Steps to Reproduce
1. Log in and visit /settings/profile
2. Change your username and click Save
3. The username is not updated in the sidebar (or in the NextAuth session object)
4. Navigating to /event-types and previewing a scheduling link results in a broken link

### Technical details
* Browser version: Chrome 92
* Node.js version: 16.5.0

**Comment by joshsny** [comment]
I have WIP for this so will submit a PR in the coming days.

My solution is to create an /api/user/ endpoint which gets the current user, then call that to get the correct username.

**Comment by baileypumfleet** [comment]
Hey Josh, great to hear you're working on a fix. As soon as you've submitted the PR, our team will review it and get it merged :)
