### ISSUE TITLE
Add input validation

### ISSUE THREAD

**Issue by emrysal** [calendso/calendso#43]
Email validation should be added to the the /book page email field. If an invalid email is given this later becomes an error whilst contacting the google calendar API.  "There was an error contacting the Calendar service: Error: Invalid attendee email.". The call fails and the booking does not show up in the agent calendar.

Expected behaviour: Invalid email should become a client side validation error.

**Comment by baileypumfleet** [comment]
Yes indeed, validation on both the frontend UI and API side is something that needs to be added.

**Comment by emrysal** [comment]
We got a couple of options like yup & joi, but I lack experience on the react side to make an informed decision. It seems to me like joi is the way to go given the ability to do clientside & serverside.
