### ISSUE TITLE
Calendar Events do not include location when scheduling with Zoom

### ISSUE THREAD

**Issue by joshsny** [calendso/calendso#447]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When setting up a Zoom meeting, the Zoom link is not included in the calendar event.

### Steps to Reproduce
1. Set up Zoom & Google Calendar integrations
2. Book a Zoom meeting through Calendso
3. The calendar event has location integrations:zoom and does not include the Zoom link. In fact, on my calendar, it includes a Google Meet link instead (which is caused by making a Conferencing Solution request)

**Comment by PeerRich** [comment]
hey @Nico-J can you give this a look as you've worked on zoom?

**Comment by Nico-J** [comment]
Hey @joshsny , hey @PeerRich , I've created a fix for this:

https://github.com/calendso/calendso/pull/638

As soon as this is merged, it'll work.
