### ISSUE TITLE
Doesn't pull busy times from Google Calendar

### ISSUE THREAD

**Issue by dnuske** [calendso/calendso#47]
Hi! very happy to discover this endeavour, try it out and post helpful bugs comments and suggestions.

In this case I notice that after you set up the slot format of the appointment type, then navigate to the public page to book an appointment it displays all slots as available, despite I have several already booked that would conflict.

In the case the app is not capable of fetching the events from the host calendar it should display some sort of error on the web interface and/or the server.

I'm on OSX Catalina. The app was installed and set up on localhost:3000.

**Comment by dnuske** [comment]
ok, I may have got that wrong. Apparently there is an error that I haven't seen. When booking an appointment the server logs say 
`API resolved without sending a response for /api/availability/dnuske?date=2021-04-18, this may result in stalled requests.`
and the front displays success, despite the API call is still `fetching`

<img width="1491" alt="Screen Shot 2021-04-17 at 22 57 17" src="https://user-images.githubusercontent.com/934511/115131692-76cb9700-9fd0-11eb-8e5c-c500f05ab18d.png">

Is it possible to run it on localhost though?

**Comment by emrysal** [comment]
The google integration AFAIK can work using localhost; but the server log error can be ignored as it is unrelated. The API resolving without sending a response however is a known issue and one that should be addressed. Have you confirmed your calendar is having events booked using your local version of Calendly?

**Comment by dnuske** [comment]
the meetings did appear, although with some delay. I'll give it a try on a server in a few days, if you want you can disregard this issue. Thank you.
