### ISSUE TITLE
Change available booking times 

### ISSUE THREAD

**Issue by bennetfabian** [calendso/calendso#48]
I personally think there isn't any reason why a 1 hour and 30 minute meeting should only be bookable every 1 hour and 30 minutes starting from 0:00. The system should be changed.

For example:
If my whole calendar is empty so there can't be colliding events, I'm still not able to book a 90 minute meeting at 14:00 even though it's logically possible.

The times shown there should be based on an API call to Google and therefore based on the real calendar. It's much more work to do but it just doesn't make any sense for the times to be generated based on event type length.

![image](https://user-images.githubusercontent.com/41294690/115132439-67644200-a000-11eb-8528-9f437d26f81b.png)

**Comment by logemann** [comment]
a lot of booking systems out there do it the same way imo.

**Comment by bennetfabian** [comment]
@logemann 
Doesn't necessarily mean it's the best way. After looking at the times on the picture, there isn't a single reason why you shouldn't be able to book a meeting at 04:00, right?

It may be a standard practice but when weighing the UX disadvantage of having too many options and the disadvantage of not being able to book meetings at a certain time, I think the latter is worse.

I personally don't even think the user necessarily needs to be able to book a meeting at certain times every 15 minutes but well, it'd be nice to at least be able to book every half hour.
May not be that much feedback but at least I got 5 people who seem to agree.

**Comment by emrysal** [comment]
In an extreme case you can have an 8 hour booking (Say you're Calendso'ing a canoe trip), that you can normally book 8-9-10 in the morning, makes little sense that you can only book 8am because the logic dictates that the next acceptable slot is at 16:00. So I agree with @bennetfabian

**Comment by bennetfabian** [comment]
@emrysal @logemann Or maybe we could add a little note and a button like "The time, you thought we could schedule our meeting, isn't listed? Request a meeting at that time." which then asks the user for a specific time and looks up if this specific time is free?

**Comment by bennetfabian** [comment]
> In an extreme case you can have an 8 hour booking (Say you're Calendso'ing a canoe trip), that you can normally book 8-9-10 in the morning, makes little sense that you can only book 8am because the logic dictates that the next acceptable slot is at 16:00. So I agree with @bennetfabian

Well that may a very extreme case but at the end we absolutely don't know who uses Calendso for which use case.

**Comment by emrysal** [comment]
I like the idea you mentioned on its own, can be a future configuration to the public view. As for this issue though; I think the appropriate solution is to implement an "Interval". Say you have a 4h meeting, you can select a 15m interval, 30m interval or 1h interval; with bookings as an example every half an hour 9:30, 10:00.. even though the meeting itself is 4h long.

**Comment by bennetfabian** [comment]
> I like the idea you mentioned on its own, can be a future configuration to the public view. As for this issue though; I think the appropriate solution is to implement an "Interval". Say you have a 4h meeting, you can select a 15m interval, 30m interval or 1h interval; with bookings as an example every half an hour 9:30, 10:00.. even though the meeting itself is 4h long.

And if one of the interval calculated times collides with an event? Maybe fetch entries in the calendar when the "booker" chooses a day and then when showing available times check for each time if it collides?

**Comment by einarmagnus** [comment]
If you start looking at this, I'd love it if you generalized to generation of intervals in the way youcanbook.me provides. They allow that you can control your availability through your calendar like this, which is super great for me:
<img width="489" alt="Screenshot 2021-07-29 at 20 20 10" src="https://user-images.githubusercontent.com/15872/127545171-880cfd6a-7d60-4ff8-a989-8afe663eee95.png"> 
They have a lot of limitations that I don't like, but this is really a killer feature.

**Comment by jippi** [comment]
Was this fixed in https://github.com/calendso/calendso/commit/9e4422ea669293d27fdf654fe06734dfcc016c9f ? Looks to be some CI work
