### ISSUE TITLE
CalDav account not working (fastmail)

### ISSUE THREAD

**Issue by claudioruiz** [calendso/calendso#481]
### Issue Summary
Is not possible to add up a Fastmail caldav account. At the moment of adding it up, the UI shows a `Error: Could not add this caldav account` error message.

### Steps to Reproduce
1. App Store > Create new app > add credentials (yes, I did check is the app-specific password ;))
2. Error.

### Technical details
* Browser version: https://www.whatsmybrowser.org/b/91H1M
* Node.js version: v15.13.0

Terminal output:

```
10:58:51.257 timeZoneName ERROR Could not add this caldav account 
 RangeError  Invalid key length
details:
{
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
}
error stack:
• cipher:119 createCipherBase
    node:internal/crypto/cipher:119:19

• cipher:138 createCipherWithIV
    node:internal/crypto/cipher:138:3

• cipher:246 Cipheriv
    node:internal/crypto/cipher:246:3

• node:crypto:138 createCipheriv
    node:crypto:138:10

• task_queues:94 processTicksAndRejections
    node:internal/process/task_queues:94:5

• api-utils.ts:84 apiResolver
    node_modules/next/next-server/server/api-utils.ts:84:5

• next-server.ts:1168 handleApiRequest
    node_modules/next/next-server/server/next-server.ts:1168:5

• next-server.ts:1021 fn
    node_modules/next/next-server/server/next-server.ts:1021:27

• router.ts:346 execute
    node_modules/next/next-server/server/router.ts:346:24

• next-server.ts:1266 run
    node_modules/next/next-server/server/next-server.ts:1266:23

• next-server.ts:566 handleRequest
    node_modules/next/next-server/server/next-server.ts:566:14

```

Thanks!

**Comment by claudioruiz** [comment]
I didn't! :O 

Now I did it (using python import secrets > s = secrets.token_bytes(32)), put it on the .env, save, but still it shows the same error message.

**Comment by kuba-orlik** [comment]
Are you using docker setup? If so, did you rebuild the container?

17 Aug 2021 17:51:19 cla ***@***.***>:

**Comment by claudioruiz** [comment]
I'm deploying it locally just cloning the repo and using Heroku postgres, not using docker.

Just checking, am I doing it right with the encryption key?

1. `python3`
2. `>> import secrets`
3. `>> s = secrets.token_bytes(32)`
4. use that # in .env after `CALENDSO_ENCRYPTION_KEY`
5. save
6. `yarn dev`

**Comment by dotesfera** [comment]
Hi, maybe this is the right issue to post. I'm having a timeout error, can anybody help?

![image](https://user-images.githubusercontent.com/30806279/134381019-324e344c-bd9a-4014-a95e-c93b5b42e712.png)
