### ISSUE TITLE
Stripe Integration

### ISSUE THREAD

**Issue by imomin** [calendso/calendso#49]
It would be nice to add Stripe connect or simple copy/paste Stripe API keys and have an option to add price to the first step "Quick Chat $5" or "Demonstration $25" and add a credit card form (Stripe Element) before confirmation.

**Comment by florianoverkamp** [comment]
Maybe this can be done with https://github.com/staart/api and https://github.com/staart/ui ? Feels like something that could plug in to each other pretty well without having to reinvent everything.

**Comment by imomin** [comment]
Thanks for sharing the link but I think implementing Stripe directly will give full control and flexibility (philosophy behind creating calendo). Also, Stripe has made it very easy to accept payment, here are some links for react, 
https://stripe.com/docs/stripe-js/elements/payment-request-button?html-or-react=react
https://github.com/stripe/react-stripe-js

**Comment by fflores97** [comment]
I mentioned this in a discussion, but maybe a more general callbacks-before-confirmation feature would allow for stripe and other payment gateway integrations, custom validations, and just about anything you want to add to the confirmation flow.

**Comment by abalasky** [comment]
Is this something I can work on as a first time contributor?

**Comment by zomars** [comment]
Would this be a per-event type configuration? I'm trying to come up to the data model.

**Comment by zomars** [comment]
Also posting this related example from the Vercel repo: https://github.com/vercel/next.js/tree/canary/examples/with-stripe-typescript

**Comment by zomars** [comment]
We have a PR ready on #717
