### ISSUE TITLE
ERROR: failed to build: exit status 1

### ISSUE THREAD

**Issue by masteradit** [calendso/calendso#490]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I clicked on the "Deploy on Railway" button given in README.md. It used to work earlier as I had used it a few months ago to deploy it on Railway.

Build logs:
```
18: Pulling from heroku/buildpacks
Digest: sha256:196527ba5bf15b6eb7e555796d096d8cb785ff4813122105886a39bc770ee5d3
Status: Image is up to date for heroku/buildpacks:18
18: Pulling from heroku/pack
Digest: sha256:5eaa3c757fe5212578386b3bb96380d962607421ef913e39a34a5a523dab37d9
Status: Image is up to date for heroku/pack:18
===> DETECTING
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
heroku/nodejs-yarn       0.1.5
===> ANALYZING
Previous image with name "registry.railway.app/385dd0f1-a187-4df5-a178-09d4d3f8e698" not found
===> RESTORING
===> BUILDING
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[Installing Node]
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.7.0

[Parsing package.json]
[INFO] Parsing package.json

[Installing yarn]
[INFO] Installing yarn@1.22.11
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.20.3 from Node
[INFO] Installing node modules
npm notice 
npm notice New patch version of npm available! 7.20.3 -> 7.20.6
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.20.6>;
npm notice Run `npm install -g npm@7.20.6` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: calendso@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm ERR! node_modules/react-dates
npm ERR!   react-dates@"^21.8.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-08-18T18_01_21_383Z-debug.log
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

### Steps to Reproduce
1) Use the Deploy on Railway button in README.md.
2) Fill the form and click on deploy.

**Comment by emrysal** [comment]
It looks like Railway is ignoring our `project.toml` file that should fix Railway to build using Yarn. But in this log I see it using npm instead. We should have our npm issues sorted out soon.

**Comment by masteradit** [comment]
Okay, thank you!

> It looks like Railway is ignoring our project.toml file that should fix Railway to build using Yarn. But in this log I see it using npm instead.

Should I report this to their support team?

**Comment by masteradit** [comment]
Hey @emrysal! I saw a few other users reporting this issue in Railway's Discord server. Looks like their team is aware of this issue. They have updated their blog article and have suggested adding this to `package.json` to lock the Node version to 14:

```json
"engines": {
  "node": "14.15.3"
}
```

Link to blog article: https://blog.railway.app/p/calendso
A commit showing the changes they have suggested to the users: https://github.com/FarazPatankar/calendso-test/commit/6513d93fb865d1e60942108b9e96749c041c9d90

**Comment by emrysal** [comment]
@masteradit we looked over the suggested changes and agreed - with the small change to not lock it down specifically to `14.15.3` - instead opting for `^14.0.0` - this has been confirmed to work with Railway as logged in https://github.com/calendso/calendso/pull/510#issuecomment-903270209

This engine requirement will be removed upon removal of react-dates from Calendso.
