### ISSUE TITLE
Time Options (AM/PM to 24h) toggle not working in events

### ISSUE THREAD

**Issue by Procuria** [calendso/calendso#494]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Time Options (AM/PM to 24h) toggle not working even though you can choose the timezone in the event.

### Steps to Reproduce
1. go to https://calendso.com/rick/quick-chat
2. use the toggle
3. be a bit sad, that it isn't working :) 

Interestingly, the switch works on the calendso.com main page, but not on the 'Users' `/rick/quick-chat` page (see GIF)
On our self-hosted instance we run into the same problem. 

### Technical details
* the latest Chrome, Firefox, Android-Chrome, Safari 
* node.js v14.17.5
* self-hosted installation behind NGINX reverse proxy 

![2021-08-18_22h16_21](https://user-images.githubusercontent.com/37988494/129967044-10748080-15a9-4261-b8e5-ada7d25a159d.gif)

Thank you for your awesome work on this project !

**Comment by emrysal** [comment]
Fixed in #495 - see: https://staging-git-bugfix-time-options-toggle-not-working-calend-so.vercel.app/staging/quick-chat?user=staging&date=2021-08-19&type=quick-chat

**Comment by emrysal** [comment]
Thanks for reporting @Procuriav 👍
