### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by marghidanu** [calendso/calendso#50]
I see this project doesn't have any official releases, how should we know about changes or versions?

**Comment by baileypumfleet** [comment]
We're not adding this yet, as we don't have an official release yet. Just clone the code at the latest point, and keep pulling new changes as they come for now.

**Comment by marghidanu** [comment]
Sorry, but I cannot use this unless I can keep track of the changes based on a release. The codebase can change at any point; I cannot really run it for our team internally.
