### ISSUE TITLE
🐛 Unable to cancel "Add a new event type" without updating availability times

### ISSUE THREAD

**Issue by harad1** [calendso/calendso#51]
If one wants to "Add a new event type", but then decides to cancel without actually adding a new event, a "Change your available times" pop-up is triggered. 

The GIF below illustrates the unintended behaviour.

![Google Chrome — CleanShotX | 2021-04-19 at 14 17 12](https://user-images.githubusercontent.com/16905768/115246474-d5525b80-a11d-11eb-8f09-b02aa17ca103.gif)

**Comment by baileypumfleet** [comment]
Resolved in latest commit. Great find!
