### ISSUE TITLE
Attempted import error

### ISSUE THREAD

**Issue by zomars** [calendso/calendso#513]
### Issue Summary

When deploying into Vercel, it throws the following error: 

```
11:16:40.555 | Attempted import error: '../../components/ui/Button' does not contain a default export (imported as 'Button').
```

### Steps to Reproduce
1. Clone the project `main` branch
2. Deploy to vercel

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Node.js version: 14

**Comment by PeerRich** [comment]
@emrysal @KATT i believe you two worked on <Button> recently?

**Comment by zomars** [comment]
@PeerRich I think the bug was introduced in a77a1505
