### ISSUE TITLE
Meeting schedule loop

### ISSUE THREAD

**Issue by cpanato** [calendso/calendso#532]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When trying to schedule a meeting the pick date selector get in a loop forever

see the video attached

https://user-images.githubusercontent.com/4115580/131122332-0e381109-8e63-402d-80cc-a03a038b1cf7.mov

using the latest code from the main branch

**Comment by aSemy** [comment]
I've encountered this issue too and I can't see a way to investigate or resolve it. 

I'm using the calendso/docker config, and the latest code. I haven't tried another deployment. 

I've tried searching through the issues but I couldn't find a similar issue @ConnorGargano, have you been able to find the one you were reminded of?

Is there any way to increase log levels so I can try and see what's going wrong?

I don't think there's a lot of test coverage which is kind of worrying! Hopefully #534 will help.

**Comment by aSemy** [comment]
I found the issue! https://github.com/calendso/docker/issues/8 From this I found out my Dockerfile was out of date. I had modified it (so it would automatically checkout the git project).

I updated it to include the latest fixes from calendso/docker, and have checked out a specific version since main is currently broken #551. The 'reload in a loop' cycle is fixed.

I would still like to see some better error handling and reporting from Calendso though. This problem (or something similar) might reoccur and I wouldn't have any idea. 

Here's the Dockerfile I'm using, in case anyone is interested

```Dockerfile


# checkout the latest version from git
FROM alpine/git as repo

LABEL stage=builder
WORKDIR /calendso

RUN git clone https://github.com/calendso/calendso.git . \
    && git checkout 1ab9d1797a0e881f723227f436dc70191511dc87 
    # https://github.com/calendso/calendso/pull/551

# --- #

# build dependencies
FROM node:14-alpine as deps

LABEL stage=builder
WORKDIR /app

RUN apk update \
    && apk add --no-cache libc6-compat

COPY --from=repo /calendso/package.json ./
COPY --from=repo /calendso/yarn.lock ./
COPY --from=repo /calendso/prisma ./prisma

RUN yarn install --frozen-lockfile

# --- #

# build the app
FROM node:14-alpine as builder

LABEL stage=builder
WORKDIR /app

COPY --from=repo /calendso .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn build
RUN yarn install --production --ignore-scripts --prefer-offline

# --- #

# run the app
FROM node:14-alpine as runner

WORKDIR /app
ENV NODE_ENV production

COPY --from=builder /app/next.config.js  ./
COPY --from=builder /app/public          ./public
COPY --from=builder /app/.next           ./.next
COPY --from=builder /app/node_modules    ./node_modules
COPY --from=builder /app/package.json    ./package.json
COPY --from=builder /app/prisma          ./prisma
COPY  scripts scripts

EXPOSE 3000

CMD ["/app/scripts/start.sh"]
```

**Comment by cpanato** [comment]
cool!

Let me try

**Comment by cpanato** [comment]
using that commit works! thanks @aSemy for the debugging!
