### ISSUE TITLE
'Disable Calendso branding' doesn't remove the branded preview image (`og:image`)

### ISSUE THREAD

**Issue by aSemy** [calendso/calendso#565]
### Issue Summary

The `og:image`/meta property image ([Open Graph protocol](https://ogp.me/)) is hardcoded and is not affected by configuration.

### Steps to Reproduce

1. I have a self-hosted Calendso instance, and 'Disable branding' is checked
    ![image](https://user-images.githubusercontent.com/897017/131972481-599be037-124e-4d56-80de-c4c9aa22a3de.png)
2. When I visit the 'booking' page, branding is disabled as expected
    ![image](https://user-images.githubusercontent.com/897017/131973229-5695c256-6ddf-464f-8f61-4be96fb7bbad.png)
3. But when I share a link to my 'booking' page in Whatsapp, the preview shows Calendso branding
    ![Screenshot 2021-09-03 094150](https://user-images.githubusercontent.com/897017/131972172-99beed07-d023-47ae-b870-421316146d58.png)

I expect that if branding is disabled, then the `og:image` should be disabled too. It would also be nice if this image was generated/customisable - but a quick fix is to remove the image if 'remove branding' is enabled.

### Technical details

I'm using [version 1ab9d1797a0e881f723227f436dc70191511dc87](https://github.com/calendso/calendso/commit/1ab9d1797a0e881f723227f436dc70191511dc87)

* image URL definition https://github.com/calendso/calendso/blob/adff0d017638bdae1fc18cc49b08425ffff4595a/lib/config/next-seo.config.ts#L5
* configuration https://github.com/calendso/calendso/blob/adff0d017638bdae1fc18cc49b08425ffff4595a/components/seo/head-seo.tsx#L38

**Comment by PeerRich** [comment]
it's a lot of complexity to fix that and very low priority. Happy to accept PRs but closed for now

**Comment by cyango** [comment]
Interested in this also. Allowing to change this image, even if with just an manual url.

**Comment by PeerRich** [comment]
yea we plan to add more logo options soon which will replace the og-image

**Comment by PeerRich** [comment]
it will also update the logo in cal video

**Comment by shibacomputer** [comment]
The docs refer to a couple of whitelabelling env vars, here: https://cal.com/docs/how-to-guides/how-to-white-label-the-self-hosted-instance

Is this related?
