### ISSUE TITLE
FR: reorder event types

### ISSUE THREAD

**Issue by aspiers** [calendso/calendso#570]
### Is your proposal related to a problem?

I've created three event types and I notice that on both my public home page https://calendso.com/aspiers and also on https://app.calendso.com/event-types the list of event types is in a fixed order (which possibly corresponds to the order in which I added them).

### Describe the solution you'd like

I'd like to be able to control the order in which they are listed on my public page.

### Describe alternatives you've considered

Couldn't find any references to this in either this issue tracker or the GitHub Discussions tab.

**Comment by ConnorGargano** [comment]
Hi @aspiers, I will put this on the engineering teams to-do list, I will keep this issue open and an update will be available accordingly.

**Comment by aspiers** [comment]
Thanks @ConnorGargano!

**Comment by emrysal** [comment]
Fixed by #1142

**Comment by aspiers** [comment]
Cool thanks, nice work @emrysal! I have just tested it out and notice that when you hover the mouse over any event type, up and down arrows always appear.  For the top and bottom ones in the list, only one arrow should appear for obvious reasons.
