### ISSUE TITLE
Broken logo in email footer

### ISSUE THREAD

**Issue by aspiers** [calendso/calendso#574]
The calendly logo in the email footer seems broken:

```html
 <img style="opacity:0.25;width:120px" src="https://ci3.googleusercontent.com/proxy/OCHl0QvUMVECLDxCCFfWbKKzOF37B-2qGcmVCis9xapQJm6lQaXQsVVj1OSrf3K5Ngp4iBBU2bfauCn-TmEsZ_Ax=s0-d-e1-ft#https://app.calendso.com/calendso-logo-word.svg" alt="Calendso Logo" class="CToWUd">
```

![image](https://user-images.githubusercontent.com/100738/132097756-a5093a88-c98c-4452-803f-ceeada042b31.png)

**Comment by ConnorGargano** [comment]
Hi @aspiers, I have had a look into this for you and can see this is all working on my end, in this case, I will close this off.

**Comment by aspiers** [comment]
@ConnorGargano Sorry, but just because it's working for you that doesn't mean there's no issue. I just tested again and I still see the broken logo as above, so there's definitely an issue.  Happy to help debug it - please can you reopen this?

**Comment by aspiers** [comment]
OK, so upon more investigation it seems that somehow the Gmail web UI is rewriting the URL inside the `<img src="...">` attribute.  Gmail certainly doesn't break other images in any of my other emails, so there's obviously something odd going on here.  I found this which appears to be the same problem:

- https://support.google.com/mail/thread/7239308/gmail-signature-images-always-break?hl=en

which leads here:

- https://support.google.com/mail/thread/2323096/failure-to-insert-image-in-gmail-signature?hl=en

which says at the bottom:

> note someone says you cannot use Scalable Vector Graphics (SVG's)

Ahah!  That would explain it.  So most likely the fix is to use a png or jpeg.
