### ISSUE TITLE
UX: suggest rename from "App Store"

### ISSUE THREAD

**Issue by aspiers** [calendso/calendso#576]
This is of course subjective, but FWIW here's my perspective as a newcomer: the term "App Store" doesn't really make sense to me, as it brings connotations of something very different to the reality.

A connection to a Google account is not an app, it's an integration.  The word "app" implies something which brings its own UI with significant new functionality, whereas integrations are well understood to mean a connection between two different platforms, based on some authorization mechanism (e.g. OAuth).

You already use the word "integration", so why not call that section of the UI "Integrations"?

**Comment by bennetfabian** [comment]
If I still remember correctly, the decision to rename Integrations page to App Store was made by the CEOs and most active maintainers of Calendso.

The intent was to make it easier to understand for people without a technical background to understand what this page is all about. The normal user who doesn't know much about technology and development may be more familiar with the term "Apps" than with "Integrations".

I think it was @PeerRich who made that change a few weeks ago.

**Comment by aspiers** [comment]
Hmm.

> The normal user who doesn't know much about technology and development may be more familiar with the term "Apps" than with "Integrations".

Yes this is true, but familiarity doesn't check the fact that the terms "Apps" and "App Store" mean something substantially different to what these integrations offer.  So if anything I would expect this familiarity to create more confusion, because users already have a very strong idea of what apps and an "App Store" are.

If "Integrations" is too technical a word (which seems unlikely because you are still using that word in the UI), how about "Connections"?  Although that could be misinterpreted as social connections, like an address book.

It's worth noting what terminology other companies use for this, e.g.

- Calendly: "Integrations"
- x.ai: "Connected calendars"

and then similar concepts in other fields:

- Zapier: "zaps"
- IFTTT: "applets" (but they are more heavyweight, as they have their own logic)
- Strava: "Partner Integrations"

I think I like "Connected calendars" best.  It's crystal clear, 100% accurate, and jargon free.

**Comment by PeerRich** [comment]
Hey @aspiers, we did in fact renamed it to App Store (and Apps) because we are working on an extensions marketplace where anyone can build apps, which may not be integrations

an integration will be a category of said app store, but other categories can be themes or other apps that change the UI.

We were inspired by Intercom which uses "App Store".

not every app will be an integration but every integration will be an app on our app store 👍

**Comment by emrysal** [comment]
I do off course agree with the naming of App Store - as I was one of the proponents; but in my testing I load our pages a _boatload_ - and you'd think that I after loading the pages at least 10,000 times would have App Store baked in my muscle memory. But for some reason I keep visiting all other pages before finding the Integrations page, because that mental map just does not work with the speed I am debugging at.

So I think the naming made sense in our minds thinking about it, but when I want to do things at speed, my mind encounters a naming error. I'm just one person though, but I'm starting to wonder (because I just can't get used to it) we'd be better off calling it "Extensions" or revert back to "Integrations" even but add a category of integration later that is an "App". (Much like a Connection in the case of Calendars)

**Comment by PeerRich** [comment]
I think extension can make sense. that's how wordpress is handling it.

**Comment by emrysal** [comment]
Worth a try, I think a good darwin test is to try "Extensions" and see if I continue to navigate the wrong page when I want to go to the calendar connections 😆

**Comment by PeerRich** [comment]
lets revert back to integrations until we have apps that are not integrations and change back to app store with proper app store functionality (search, categories, submit an app, etc)

**Comment by bennetfabian** [comment]
That really sounds like the best option there is. Let's see how our awesome project progresses and discuss the definitions and titles of certain pages later.

**Comment by PeerRich** [comment]
that being said, it will likely end up being "app store" because apps will be added that either have their own UI or change existing UI. its more a question of when. until then i am pushing a PR to revert back to "Integrations"

**Comment by bennetfabian** [comment]
Most important is that we don't miss anything when changing it. With that, I mean things like documentation and so on. You could conclude that App Store changed to Integrations and later back but we should remember keeping documentation etc. up to date with us changing terms.

**Comment by PeerRich** [comment]
a proper App Store update would receive enough explanation and changes in the documentation for it

**Comment by bennetfabian** [comment]
Also we must make sure that there are no legal problems. As far as I know, Apple registered App Store as a trademark in the whole European Union.

See: 
- https://register.dpma.de/DPMAregister/marke/registerHABM?AKZ=007078314
- https://register.dpma.de/DPMAregister/marke/registerHABM?AKZ=009852691

**Comment by PeerRich** [comment]
intercom.com is a much bigger company and they're doing just fine. would be surprised to be fair but obviously good point to look out for.

![image](https://user-images.githubusercontent.com/8019099/132110369-698f624f-7555-42b6-afb3-29ea06f7d102.png)

**Comment by bennetfabian** [comment]
You never know. Sometimes big corporations just go crazy.
Remember when YouTube actually took down Youtube-DL and received massive backlash from GitHub's whole community. 😉

**Comment by PeerRich** [comment]
reverted

![image](https://user-images.githubusercontent.com/8019099/132110466-f3e5629b-8129-44ac-a7d2-5a569df57a80.png)

**Comment by emrysal** [comment]
Could be that they are playing a game of whack-a-mole. If I were intercom and Apple did [this](https://www.irishtimes.com/business/technology/who-s-the-real-slim-shady-intercom-or-apple-1.4383148) to me, I'd use "App Store" in retribution - they sue me I sue them..
