### ISSUE TITLE
Default working hours aren't sensible

### ISSUE THREAD

**Issue by aspiers** [calendso/calendso#577]
When I originally signed up, IIRC the start and end times of the day defaulted to midnight.  Clearly this isn't sensible.  I know that everyone has different daily routines, but no one is available 24 hours a day :-)  Why not default to 9am-5pm or something like that?  Then it would be easier to adjust to the right schedule.

**Comment by emrysal** [comment]
This has now been fixed in latest with a new onboarding flow that contains this screen: Closing this as I'm assuming that suitably fixes it 👍 

![image](https://user-images.githubusercontent.com/1046695/132105997-28a0053a-7006-48bc-b30c-1992dfe20dfa.png)

**Comment by aspiers** [comment]
Great work!
