### ISSUE TITLE
Error while seeding:  Unique constraint failed on the fields: (`id`)

### ISSUE THREAD

**Issue by zomars** [calendso/calendso#596]
This is happening when running on master as per today: `yarn dx`
 
https://github.com/calendso/calendso/blob/3d0429d172abe2cf58c1d8b927de484893d69a81/scripts/seed.ts#L27

```
$ yarn ts-node scripts/seed.ts
$ ts-node --compiler-options "{\"module\":\"commonjs\"}" scripts/seed.ts
👤 Upserted 'free' with email "free@example.com" & password "free". Booking page 👉 http://localhost:3000/free
        📆 Event type 30min, length 30: http://localhost:3000/free/30min
        📆 Event type 60min, length 30: http://localhost:3000/free/60min
👤 Upserted 'free-first-hidden' with email "free-first-hidden@example.com" & password "free-first-hidden". Booking page 👉 http://localhost:3000/free-first-hidden
PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: 
Invalid `prisma.eventType.upsert()` invocation:


  Unique constraint failed on the fields: (`id`)
    at cb (/Users/zomars/Sites/calendso/node_modules/@prisma/client/runtime/index.js:36063:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2002',
  clientVersion: '2.30.2',
  meta: { target: [ 'id' ] }
}
```

**Comment by PeerRich** [comment]
hey @zomars, we'll look into it! Thanks :)

**Comment by KATT** [comment]
Ah, yeah - this is because the seed data previously created `eventTypes` with fixed `id`s `1`/`2`/... which clashes with the autoincrement in postgres.

This is only for development seed data.

**Two possible workarounds:** 

- `yarn db-nuke && yarn dx` <-- resets your local db
- delete all rows in `EventType`-table


Let me know if this works and close the issue.

**Comment by zomars** [comment]
@KATT `yarn db-nuke && yarn dx` worked fine. Thanks! Should I close this with a PR to the docs to add a note?
