### ISSUE TITLE
`handleLegacyConfirmationMail` doesn't exist anymore

### ISSUE THREAD

**Issue by zomars** [calendso/calendso#598]
https://github.com/calendso/calendso/blob/3d0429d172abe2cf58c1d8b927de484893d69a81/pages/api/book/confirm.ts#L74

This is causing to error when trying to confirm a booking.

**Comment by emrysal** [comment]
Woops! I applied a personal rule to never include from another page! Obviously this is not reality, hotfix incoming.

**Comment by zomars** [comment]
Also from Vercel dashboard on deploy:


```
10:45:55.435 | Attempted import error: 'handleLegacyConfirmationMail' is not exported from './[user]' (imported as 'handleLegacyConfirmationMail').
-- | --
```
