### ISSUE TITLE
can't change anything on profile page (hosted plan)

### ISSUE THREAD

**Issue by jimi-henning** [calendso/calendso#608]
### Issue Summary
when i try to change anything on the profile page i get the error:
"Something went wrong
Username already taken"

### Steps to Reproduce
1. login
2. click settings (profile tab)
3. (change "about" or "first day of the week")
4. click on "save"
5. get Error: "Something went wrong. 
![2021-09-08 16_48_26-Window](https://user-images.githubusercontent.com/90334457/132532546-fa356108-2335-4121-b43c-7dede260d3e6.png)
Username already taken"

i never changed my username and i don't want to change it.

### Technical details
* Browser version: Brave (Chrome 93)
* paid hosted plan

**Comment by PeerRich** [comment]
weird, i am not getting this error. Maybe in fact your username is taken and somehow it it caused a double registration? 🤔 

![image](https://user-images.githubusercontent.com/8019099/132534921-6ec21eab-adc1-4e58-b12b-8e144b72f239.png)

**Comment by jimi-henning** [comment]
check the loom: 

https://www.loom.com/share/6d409f3e33554eec907276a41a068f4e

**Comment by PeerRich** [comment]
thank you for the loom. Let me run this by the engineering team. can more people reading this test in their account if this error happens, too? it's working for me

**Comment by jimi-henning** [comment]
i tried some stuff:

it works on firefox
BRAVE seems to be the problem

**Comment by emrysal** [comment]
@jimi-henning For some context - in some browsers the browser added form fields to the API profile update request - if they included the username this username was checked by the API - and the API checked the database for whether that username existed somewhere.

This has now changed so it allows setting the username to the same username if it is the only instance of that username in the database.
