### ISSUE TITLE
[bug] Copying event link includes double slashes

### ISSUE THREAD

**Issue by cassidoo** [calendso/calendso#642]
### Issue Summary
If you click "Copy Link" under Event Types, you get a link that has a double slash in it, for example: `https://calendso.com//username/meeting`

### Steps to Reproduce
1. Go to /event-types
2. Click on "Copy Link"
3. Look at the clipboard

### Technical details

I think the culprit is this line here:
https://github.com/calendso/calendso/blob/2574006f07fe90f0538b73e40024c5f474f49079/pages/event-types/%5Btype%5D.tsx#L845

This could potentially be a good first issue to check if the host has a trailing slash, and then not include the double slash if so. It might be elsewhere, but this was just an initial search!

**Comment by PeerRich** [comment]
great find!

**Comment by syedmdsaifihassan** [comment]
Hey @PeerRich, I would like to work on this issue, please let me know if it is not assigned to anyone.

**Comment by PeerRich** [comment]
do it :)

**Comment by syedmdsaifihassan** [comment]
Okay, Thank You :)

**Comment by meehawk** [comment]
Can I take this up?

**Comment by saurabh-619** [comment]
This issue seems to have been resolved. Is there any reason why it's still open? @PeerRich
