### ISSUE TITLE
[bug] Users can make "negative" availability ranges

### ISSUE THREAD

**Issue by cassidoo** [calendso/calendso#643]
### Issue Summary

I discovered this on accident by trying to make a meeting range from "9am to 5pm" but really it was 9am to 5am, like so:

![image](https://user-images.githubusercontent.com/1454517/133310439-b5ece5d3-3dc2-4c07-886d-5fcba22d3d9a.png)

Users should be prevented from doing this. By allowing it, it makes for 0 availabilities when you share links.

### Steps to Reproduce
1. Go to one of your event types
2. Click "show advanced settings"
3. Add an availability with the second number lower than the first
4. Share your link, note there are no availabilities

**Comment by ganeshmani** [comment]
@PeerRich I would like to work on this issue. let me know

**Comment by PeerRich** [comment]
yes please :)

**Comment by SBagaria2710** [comment]
I see this issue hasn't been assigned yet @PeerRich

**Comment by PeerRich** [comment]
assigned to @ganeshmani

**Comment by PeerRich** [comment]
oh actually hold on. @emrysal you're rebuilding this entire page, right?

**Comment by Graviis** [comment]
@PeerRich this is already solved, right?

**Comment by PeerRich** [comment]
yes
