### ISSUE TITLE
zoom: Invalid redirect URI

### ISSUE THREAD

**Issue by agordhandas** [calendso/calendso#656]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
The oauth url generated for zoom is: 
`https://zoom.us/oauth/signin?_rnd=1631722700681&client_id=94vyzcflQW2KJY_d8SajQ&redirect_uri=https%3A%2F%2Fapp.cal.com%2Fapi%2Fintegrations%2Fzoomvideo%2Fcallback&response_type=code&_x_zm_rtaid=W9zBQSIKTY-OU3M7w8o3aA.1631722700680.02664c84ea2264c74f50a043973c9262&_x_zm_rhtaid=714`

Looks like the redirect uri has not been registered with zoom:

<img width="436" alt="Screen Shot 2021-09-15 at 9 26 48 AM" src="https://user-images.githubusercontent.com/9876060/133472315-84116d3d-f17a-4de4-8545-21af1cab3b28.png">

### Steps to Reproduce
1. Went to: https://app.cal.com/integrations
2. Clicked on `Connect a new app`
3. Clicked on Add next to Zoom

### Technical details
* Browser version: Firefox 92

**Comment by ConnorGargano** [comment]
Hi @agordhandas,

We are still awaiting Zoom to approve our application. As soon as this is complete this should work.
We should not be waiting much longer!

Thanks Connor
