### ISSUE TITLE
Make event type editable

### ISSUE THREAD

**Issue by uxdmitryn** [calendso/calendso#658]
### Is your proposal related to a problem?

Unable to edit event type, which leads to this slight bit of weirdness: https://twitter.com/dmitryn/status/1438190906352574472/photo/1

### Describe the solution you'd like

Make event type field editable.

### Describe alternatives you've considered

N/A

### Additional context

Hopefully this field isn't non-editable because you're using it as a unique ID. If so, I would reconsider. :)

**Comment by ConnorGargano** [comment]
Hi @uxdmitryn,

You should be able to edit event types.

Can you refer to the following documentation to resolve the issue
https://docs.cal.com/docs/event-types#editing-an-event-type

If you are still having issues with this then let me know and we will have a further look into this for you!

Thanks Connor
