### ISSUE TITLE
add support for account deletion

### ISSUE THREAD

**Issue by philippdormann** [calendso/calendso#666]
### Is your proposal related to a problem?
No

### Describe the solution you'd like
Due to GDPR (and a basic understanding of privacy) there should be the possibility to delete my account

**Comment by PeerRich** [comment]
Oh that was lost in the last development cycle. Will add later today!

**Comment by PeerRich** [comment]
nvm @baileypumfleet will work on this

**Comment by 3-w-c** [comment]
Any advice on manually deleting users in the meantime? Is it enough to delete the row from the `users` table or will that break things?

**Comment by philippdormann** [comment]
closed in PR #1403 🤫

ref #1443
