### ISSUE TITLE
Meeting Location in the Booking page still uses the Calendso.com domain

### ISSUE THREAD

**Issue by MichaelNey** [calendso/calendso#671]
### Issue Summary
When you go to a Booking page (ex: https://cal.com/peer/book?type=127&date=2025-09-30T23%3A00%3A00-07%3A00) the location is still using the calendso.com domain.

![image](https://user-images.githubusercontent.com/25756024/133601466-2c6c07b0-4ff8-418c-a7c3-770378393c48.png)

### Steps to Reproduce
1. Go to a user's page such as: https://cal.com/peer
2. Select a meeting option, date, and time.
3. See the booking details location.

To go along with the rebrand, it may make sense to have this display the cal.com domain instead.

### Technical details
I believe the location is coming from this Prisma call for the eventType that gets passed into the Booking component props object.

Prisma call to get the locations:
https://github.com/calendso/calendso/blob/7ae85fefeef878b535b56a9b47c7081decce02be/pages/%5Buser%5D/book.tsx#L39

BookingPage component uses the locations:
https://github.com/calendso/calendso/blob/7ae85fefeef878b535b56a9b47c7081decce02be/components/booking/pages/BookingPage.tsx#L31

**Comment by PeerRich** [comment]
this was a manual input by me. changed it
