### ISSUE TITLE
Event Level Availability seems to be getting overriden by Profile Level Availability

### ISSUE THREAD

**Issue by Naman-Bhalla** [calendso/calendso#684]
### Issue Summary
Created an event with availability 5 PM to 8 PM on Saturday and Sundays. My profile had availability from 1 PM to 6 PM daily. 

#### Screenshot of Event Settings Page:

![image](https://user-images.githubusercontent.com/6305474/133891929-95135756-c4e7-4c6a-b86e-44247d06ff4c.png)

#### Screenshot of Availability Settings Page:

![image](https://user-images.githubusercontent.com/6305474/133891963-507ae8df-9099-4cad-ad66-bc8a10ad445d.png)

#### Screenshot of Event Page:

![image](https://user-images.githubusercontent.com/6305474/133891999-9372c499-1849-4344-b099-a78c4242aa03.png)

### Steps to Reproduce
1. Create an account on cal.com (The issue can be reproduced on a self deployed version as well).
2. Setup working hours.
3. Create an event with specific availability timings.
4. Change availability timings from your account.
5. Observe the discrepancy on event page!

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

#### Expected Behaviour:
The availability on event booking page should have been 5 PM to 8 PM on Saturday and Sunday.

#### Observed Behaviour:
The availability on event booking page is 1 PM to 6 PM daily.

**Comment by ConnorGargano** [comment]
Hi @Naman-Bhalla 
We have had some issues with availability recently, I have had a little look at availability on my end and all looks to be working fine now. Would you be able to have another look for me and if the issue is still active let me know.
-Thanks Connor
