### ISSUE TITLE
[BR] No min-max value in place for StartTime and EndTime in "Change available time"

### ISSUE THREAD

**Issue by SBagaria2710** [calendso/calendso#687]
### Issue Summary
No min-max set for `StartTime` and `EndTime`. Users are able to set time slots outside the range of 24 hour system.
Please, refer the screenshot attached.

<img width="1071" alt="Screenshot 2021-09-18 at 9 55 23 PM" src="https://user-images.githubusercontent.com/33802361/133895734-7ed53a4b-49b0-4350-a5de-9994fb728372.png">

Notice at the text: `Currently, your day is set to start at 30:00 and end at 25:00`

### Steps to Reproduce
1. Went to `https://app.cal.com/availability`
2. Clicked on `Change available times`
3. Set the StartTime and EndTime to any number.

Same can be reproduced on the local app as well.

Even though, users are not given the option to choose in between 12 hour system and 24 hour system, users should be checked for entering the wrong time. It might a mistake from user end, but it shouldn't have happened.

Since, we are not handling this **`StartTime` can be greater than `EndTime`**. Which again doesn't make much sense.

### Technical details
* Browser version: Chrome 93
* Node.js version - v14.17.6

**Comment by SBagaria2710** [comment]
I'd like to fix this issue if you guys allow me 🙇🏼

**Comment by emrysal** [comment]
Having implemented the new /availability edit page; this is now fixed as the old start and endtimes are deprecated. 👍
