### ISSUE TITLE
Page Crashed 👉🏼  availability troubleshoot

### ISSUE THREAD

**Issue by SBagaria2710** [calendso/calendso#690]
### Issue Summary
Page Crashed!

<img width="1920" alt="Screenshot 2021-09-18 at 10 35 08 PM" src="https://user-images.githubusercontent.com/33802361/133896815-5cc12ce2-1c52-422f-94de-d4571a308e9c.png">

### Steps to Reproduce
1. Went to [Availability troubleshoot](https://app.cal.com/availability/troubleshoot)

Page shouldn't have crashed no matter what.

### Technical details
* Browser version: Chrome 93
* Node.js version: 14.16.7

**Comment by PeerRich** [comment]
hey there, troubleshooter is currently broken and we're working on replacing it with a better system

**Comment by SBagaria2710** [comment]
Oh! Would it be possible to hide it in production 😅 
If you want, I can raise a PR for hiding the `troubleshooter card` :)

**Comment by PeerRich** [comment]
this page is getting a complete remake this week

**Comment by PeerRich** [comment]
but yea, feel free to remove the card for now!
