### ISSUE TITLE
Uploading a profile picture throws an error

### ISSUE THREAD

**Issue by ShreyashVerma01** [calendso/calendso#698]
### Issue Summary
Uploading my profile picture throws an error. It throws the error when I don't crop the image and the site does not change the profile picture, but it changes the profile picture if I crop it.  

### Steps to Reproduce
1. Went to Settings Page
2. Clicked on the "Change Avatar" button
3. Chose picture as my profile picture
4. Clicked the "Save" button
5. Throws the error

### Technical detail
* Error is shown above the Username tab - 'Unexpected token E in JSON at position 0'
* Dimension of the picture that I wanted to upload as my profile picture - 1867 × 2185

**Comment by ConnorGargano** [comment]
Hi @ShreyashVerma01,
Looks like this is all working and no issues are happening for this.
I will close this issue as I have now tested this however if you are still having issues please let me know.
-Thanks Connor
