### ISSUE TITLE
Availability does not get applied to account when setting it in registration wizard

### ISSUE THREAD

**Issue by bttger** [calendso/calendso#700]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I just created my account on cal.com and noticed that the availability times that I set through the registration wizard after the first login were not applied.

### Steps to Reproduce
1. Register for a free account
2. Log in for the first time
3. Start the wizard and fill out the name
4. Dont connect any integration and go to the availability times
5. Skip to first step in wizard again (here I also noticed that my name got deleted after skipping to the previous page)
6. Fill out the name again
7. Skip to availability times and confirm them (I think it was that my day ends at 17)
7. Skip to the end and confirm, open the admin dashboard
8. Open the first event and see that the availability times are from 0-24 instead of the working hours

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect that the availability times are applied to my account. Also, I dont know how to set the weekdays at which I am available, I only see the option to set the time (which I guess applies to every weekday?)

### Technical details
* Browser version: Chrome Version 93.0.4577.82 (Official Build) (64-bit)

**Comment by starlocke** [comment]
The same thing happens with a self-hosted, Docker-based edition of this system that I deployed just now.

Commit `b0ad3775176a8561c9133d2e566189a1ec3062d0` of https://github.com/calendso/docker, for reference.

**Comment by starlocke** [comment]
I thought maybe it was just a slightly annoying "you have to configure it more deeply" thing, since I found that each event-type has an "advanced" setting to do fine-grained availability controls, but, those didn't give the effect that I intended of restricting availability to Monday-Friday business hours except-lunchtime.

![000072](https://user-images.githubusercontent.com/1019999/133942620-c7dcb7d2-8c74-452d-b0d7-e16e8da04d8f.png)

**Comment by bttger** [comment]
> The same thing happens with a self-hosted, Docker-based edition of this system that I deployed just now.

Thanks for verifying it.

> since I found that each event-type has an "advanced" setting to do fine-grained availability controls

I also opened the advanced settings for an event but I honestly was confused because I only saw the timezone dropdown and didn't even notice the "Add another" button. For me it is not intuitive what that button does, maybe this should be improved from a UX perspective.

And, you are right, it should also be possible to ignore lunch time in the availability. This is definitely another bug, because the times in the opened event make no sense at all (I just set one of my events to the same availability settings as in your screenshot). Do you want to open a bug report for that?

**Comment by starlocke** [comment]
Hm... perhaps we're talking about slightly different "availability times" systems at play, between my report and the original report. A little bit hard to say without screenshots and more analysis. Anyway -- originally, I thought we were both reporting that "customized" availability times (with day-of-week) weren't being handled properly. However, it's true that there are some issues with user accounts also having "availability" as a separate technical concept within the code/database (ie: the special columns that default to 0h-23h, more or less).

**Comment by ConnorGargano** [comment]
Hi @bttger 
This has been a recent issue but has now been resolved, could you please give this another go and if the issue still occurs then please let me know!
-Thanks Connor
