### ISSUE TITLE
Availability times are not working

### ISSUE THREAD

**Issue by shunkakinoki** [calendso/calendso#718]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I put Sunday as a non-available time yet it shows that it's available. Need a fix asap.

### Steps to Reproduce
1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
* Node.js version
* Anything else that you think could be an issue.

**Comment by ConnorGargano** [comment]
Hi @shunkakinoki,
This has been a recent issue but has now been resolved, could you please give this another go and if the issue still occurs then please let me know!
-Thanks Connor

**Comment by sbw78** [comment]
I am also encountering this issue. 

Browser: Firefox 93 on OS X 10.15.7; Safari v15
Node.js v16.13.0
