### ISSUE TITLE
All booked display error

### ISSUE THREAD

**Issue by angel8au** [calendso/calendso#726]
👍

### Issue Summary
All booked display error

### Steps to Reproduce
1. I fulled my calendar in google calendar 
2. Then when i try to make an apoiment the day that is booked, a display text can not read properly. 
![Captura de Pantalla 2021-09-22 a la(s) 2 03 41 p m](https://user-images.githubusercontent.com/37971517/134414285-5baab113-4dd3-423a-8b18-6e79ad16f4ed.png)

**Comment by PeerRich** [comment]
yes. that's what's causing it. I'll ship a hot fix for it
