### ISSUE TITLE
Login: "Something went wrong"

### ISSUE THREAD

**Issue by kelvinalfaro** [calendso/calendso#760]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Running my own deployment via railway.app
Everything was working up until a few days ago. 
Latest deployment won't allow login. 

A summary of the issue. This needs to be a clear detailed-rich summary.

"Something went wrong." Error message is presenter in training to sign in. 

### Steps to Reproduce

1. (for example) Went to ... Cal.alfaro.io
2. Clicked on... Entered login details, clicked sign in. 
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
 Should result in bring able to sign in

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
- furefox, chrome, edge
- Node.js version
- Anything else that you think could be an issue.

**Comment by emrysal** [comment]
Login functionality now requires a new environment variable called `JWT_SECRET`. We recommend setting this value to some kind of hash, an example could be `JWT_SECRET="b6182e2660addf13ec964a5c512c2f5d35d52da8"`.

**Comment by jstrellner** [comment]
Unfortunately @emrysal, this didn't work for me.  I seem to be having the exact same issue as @kelvinalfaro (same platform, everything).

**Comment by jstrellner** [comment]
Actually @emrysal, based on the network response to the `credentials` file, I think its my database.

```
{"url":"https://schedule.everwall.com/api/auth/error?error=The%20column%20%60users.locale%60%20does%20not%20exist%20in%20the%20current%20database."}
```

Going to try running [the database migration](https://developer.cal.com/docs/migrations) to see if that fixes it.

**Comment by emrysal** [comment]
@jstrellner Yes that's the other part of this, generally whenever doing a sync with main run:

```
yarn install && \
npx prisma deploy migrate
```

**Comment by jstrellner** [comment]
@emrysal Thanks.  I know this isn't a support site, but `npx prisma migrate deploy` returns an error:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "railway", schema "public" at "containers-us-west-1.railway.app:7518"

36 migrations found in prisma/migrations
Error: P3005

The database schema for `containers-us-west-1.railway.app:7518` is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline

exit status 1
```

Looking at your docs, you talk specifically about this and mention that all past migrations are in `_prisma_migrations`, yet I do not even have that table at all. Any idea on how to resolve that?

When I ran the initial install yesterday, it didn't seem to create that table.

**Comment by emrysal** [comment]
Railway still uses the `npx prisma db push` method. That'll work if you have an unused database, I'll share a snippet I wrote to auto-sync prisma migrate with `--applied` tomorrow. Using `npx prisma migrate deploy` we are able to create custom migrations that ensure data stays intact between refactors, `npx prisma db push` I would therefore not recommend.

**Comment by jstrellner** [comment]
@emrysal Something that sets migration thing up after the initial deploy would be awesome!

As for me, I was able to get it up and running, and I hope the following fixes the issue for @kelvinalfaro too.

### Here is what I did (going a bit further behind where I joined this conversation for context):
1. From within my local fork I ran `git remote add upstream https://github.com/calendso/calendso.git` to add this repo as upstream.
2. After my merge failed when doing `git merge upstream/main`, I ran `git merge upstream/main --allow-unrelated-histories`.  This gave me a ton of merge conflicts, but I accepted all of them from "their" version.
3. Make sure that JWT_SECRET is listed as a custom variable with a sha1 string of something as the value.
3. I pushed my local main to origin/main. This sets off Railway building it.
3. Then, I looked at the file diff for all files in /prisma/migrations (in my case i saw 4 new files)
4. I ran `railway run npx prisma migrate resolve --applied [folder name]` for each folder that wasn't one of the 4 new folders from my merge.
5. 32 times running that command later, I ran `railway run npx prisma migrate deploy` and it migrated those 4 folders that were listed in the diff.
6. It works!

Thanks for all your help @emrysal.

**Comment by artistro08** [comment]
I was just getting started and can say that these tidbits helped. Mainly the `JWT_SECRET` and merging from upstream. Thanks @jstrellner

**Comment by kelvinalfaro** [comment]
Thanks, Everyone. @emrysal and specially @jstrellner for your support. @jstrellner your walk thought was super helpful.

**Comment by PeerRich** [comment]
I believe this is fixed.
