### ISSUE TITLE
Can't pull calendar even after Google Integration 

### ISSUE THREAD

**Issue by XaviSmith** [calendso/calendso#77]
Hey, I posted about this in the Slack channel but got no response

I managed to go through setup and add the Google Calendars integration and set busy times/make a new event type all on localhost, but nothing's changed for the website in general? I just see the following when I go to the Dashboard, Integration, and Availability pages 
<img width="1270" alt="Screen Shot 2021-04-20 at 11 54 56 AM" src="https://user-images.githubusercontent.com/10490713/115427798-c88e4000-a1cf-11eb-801c-7c9e5183d2c9.png">

<img width="1410" alt="Screen Shot 2021-04-20 at 11 57 12 AM" src="https://user-images.githubusercontent.com/10490713/115427831-cd52f400-a1cf-11eb-933c-ebe95653064b.png">

<img width="1438" alt="Screen Shot 2021-04-20 at 11 57 22 AM" src="https://user-images.githubusercontent.com/10490713/115427856-d2b03e80-a1cf-11eb-89d2-20bac4d205e7.png">

<img width="1433" alt="Screen Shot 2021-04-20 at 11 57 30 AM" src="https://user-images.githubusercontent.com/10490713/115427871-d5129880-a1cf-11eb-8cb3-a9f4ae585e2e.png">

**Comment by baileypumfleet** [comment]
Are you saying that the booking pages don’t work?

**Comment by XaviSmith** [comment]
I haven't/can't see any booking page or any mention of it, I'm not sure where to go from here

**Comment by emrysal** [comment]
Hi @XaviSmith If you go to your calendly URL (go to profile, look at username); you'll get to a public booking page which is what you are configuring within the control panel.
