### ISSUE TITLE
Unable to send meeting invites

### ISSUE THREAD

**Issue by shreyash-sharma** [calendso/calendso#776]
### Issue Summary

Integrated both Google Calendars and Zoom, but I after the email is sent to the recipients I am unable to see anything in the meeting's "where" field. 

How to send meeting location, either Google meet or Zoom to attendees?

**Comment by ConnorGargano** [comment]
Hi @shreyash-sharma,
As you mentioned, your integrations have been connected but for a meeting location to be sent to yourself and the recipient, you must have set the location within your event type.
You can find out how to do this here: https://docs.cal.com/docs/event-types/edit-an-event-type.
If this has not resolved your issue please let me know.
-Thanks Connor
