### ISSUE TITLE
Integration -> Connect a new App -> error : you must be logged in

### ISSUE THREAD

**Issue by mani9896** [calendso/calendso#787]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On trying to Connect google calender in integration , after allowing and selecting the google account error is displayed as .
![image](https://user-images.githubusercontent.com/54025138/134862425-2d3f4140-c3c8-4e3f-ab73-140e96c6c84d.png)

### Steps to Reproduce

1. Go to intgerations
2. Cick on Connect New App 
3. Select Google Calender
4. Select account and proceed .
5. Error Appears

- Browser version: Firefox 92
- Node.js v14.17.5

**Comment by baileypumfleet** [comment]
I'm going to close this off as we can't replicate this issue on our production and preview environments. If you find any more details, please reopen and we will look into this further :)
