### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by nmiculinic** [calendso/calendso#788]
### Issue Summary

I've tried to run the solution locally. It failed on node engine version constraint

### Steps to Reproduce

1. git clone
2. yarn

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

- Node.js version

 ▲ node --version
v16.8.0

- Anything else that you think could be an issue.

**Comment by baileypumfleet** [comment]
Node.js should now be locked in the project to version 14.x. Could you please try again?

**Comment by nmiculinic** [comment]
I got it working with nvm and setting node to version 14. I...don't usually use node, thus had to do some googling to get it working

**Comment by nmiculinic** [comment]
Thanks for the help!
