### ISSUE TITLE
Auto-build docker images as part of the CI

### ISSUE THREAD

**Issue by nmiculinic** [calendso/calendso#789]
The docker images should be built as part of the (release) CI pipeline and pushed to registry; (you can use GitHub registry fwiw)

### Describe the solution you'd like

* Use of many pre-packages Github actions for building docker images & pushing them to registry
* It's relatively easy to do, some googling and some copy-paste

**Comment by baileypumfleet** [comment]
Please re-create this issue in our Docker repository (calendso/docker)
