### ISSUE TITLE
Able to book a slot that conflicts with a smaller event within the slot

### ISSUE THREAD

**Issue by emrysal** [calendso/calendso#79]
Bit of an accidental find; When booking a slot, if the slot being booked > the length of an existing event E.g. I have an event in my calendar from 9:15 until 9:30, this is properly blocked from booking in 15 minute booking slot times, but if I by chance have 1-hour event types as well, I am still able to book 9:00-10:00. This is due to the code checking whether the slot you are booking time is between the start and end busyTime, but not whether the slot you are booking overlaps with a smaller, other event.

**Comment by harad1** [comment]
I think this is part of a larger issue that will need addressing. At the moment, we are not doing any verification via Google Calendar API as to the busy/available times. You could have an event booked on your calendar, and those slots would be still available via Calendso. 

Thus, I think, if we tackle the issue of "is that slot _actually_ available", then that will also solve the issue of a larger & smaller event conflict. What do you think, @emrysal?

**Comment by emrysal** [comment]
This is indeed fixed nowadays :)
