### ISSUE TITLE
Time zones inconsistencies & duplicate entries. 

### ISSUE THREAD

**Issue by harad1** [calendso/calendso#80]
Recently, a new time zone feature was contributed 👏. Whilst this was a very welcome contribution, I think there are currently too many time zones — unnecessarily cluttering the code and the dropdown. I can see that the inspiration was drawn from [here](https://stackoverflow.com/questions/56048877/cant-set-select-menu-value-with-jquery), but I'd make some changes to the options available. For example, at the moment, we have 13 different Argentinian cities, despite Argentina having [one time zone](https://www.timeanddate.com/time/zone/argentina)... 

![image](https://user-images.githubusercontent.com/16905768/115470936-0d958f00-a22f-11eb-91bc-0d1c293aa09b.png)

We also have now three "Americas". US at the top, and then "America", which has both Latin American cities and ... Canadian cities, like Toronto. There is also inconsistency regarding time zone abbreviations - US ones have abbreviations of the time zones they are in, and the rest does not. Whilst I can appreciate why abbreviations could be high-maintenance as UK is in GMT but changes into BSM between March and October, it's either all or none, for the sake of consistency, imo. 

![image](https://user-images.githubusercontent.com/16905768/115471640-366a5400-a230-11eb-9176-c6758fbce715.png)

Therefore, I'd refactor this by removing unnecessary entries, clean up the inconsistencies and ideally merge some options, as for example, Central European Time is used by the vast majority of European countries, with few exceptions, and yet every single country appears separately. Usually, for example, Dublin and London appear under the same option, since they are in the same time zone (with Ireland also switching into Irish Standard Time between March and October). 

![image](https://user-images.githubusercontent.com/16905768/115472132-22732200-a231-11eb-8089-7af803ee9c49.png)

I am raising this as an issue, as I don't want to change things around myself as I wasn't the one implementing them — happy to discuss it further and change it myself if there are no volunteers.

**Comment by baileypumfleet** [comment]
PR is merged

**Comment by 50bbx** [comment]
This is a breaking change. I have `Europe/Rome` set on the database and now of course is missing from the list (no big deal).

I tend to disagree, as even if the timezone is the same between Rome and Amsterdam, it is now hard to find the right timezone because I always look for the only one in my country (Italy) which is Rome. The list was alphabetically sorted but now I need to read every line.

I understand that there can be a single timezone for Argentina like `America/Argentina/Buenos_Aires`, but the same should hold true for every country and not for every timezone.

Also, what are the criteria for grouping cities in these two options?
![image](https://user-images.githubusercontent.com/3308680/115879215-b4557780-a449-11eb-86a5-63222f532508.png)
![image](https://user-images.githubusercontent.com/3308680/115879254-bc151c00-a449-11eb-957f-6bd8f7fa8189.png)

**Comment by harad1** [comment]
If you do it by country, then you will end up with vastly different timezones next to one another, as it was the case with US initially. But if you do it by timezone, then you may have the same country spread out on the list. 

I think the question is: would more people look for their timezone or for their country/city. I think the issue with doing it by city, as it was the case for the US, is that it's not entirely accurate — someone living in the Eastern Timezone could live anywhere from Miami to Indianapolis, so saying "New York" is ignoring 1/4 of the US in the Eastern Timezone, as an example. I can understand why someone would want to do it by city, if they lived in a smaller country, like the UK, but then you have countries with multiple timezones where ordered-by-city simply doesn't work, imo.

**Comment by emrysal** [comment]
Hi @50bbx Fair comment about breaking change; it shouldn't break functionality in the backend as the database still works properly; it'll just default to "can't find timezone anymore" in the UI.

Let's work together on this; it's very complex and there's no simple solution here, I suggest we move away from developing our own solution as I'm realising it's beyond expectation complex and move to something like: https://github.com/ndom91/react-timezone-select

**Comment by 50bbx** [comment]
@emrysal yes, I agree with you. I believe that a component like react-timezone-select would be our best option, mainly because it helps narrow down user search by first sorting the list by timezones.

**Comment by baileypumfleet** [comment]
I've just had a look at react-timezone-select and I believe that would be a great option :)
