### ISSUE TITLE
Calendar shows no availability for any month

### ISSUE THREAD

**Issue by joshtemple** [calendso/calendso#805]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

All meeting dates are disabled/unclickable in every month, implying that there's no availability.

![image](https://user-images.githubusercontent.com/8672171/135001363-62f369fa-e0ea-405e-971d-bfa74f71ed8b.png)

The troubleshooter _does_ seem to recognize the correct availability:

![image](https://user-images.githubusercontent.com/8672171/135001515-dce1a66b-67d0-4362-973c-0b51d441c47e.png)

### Steps to Reproduce

1. Deployed on Railway (production) following their tutorial (needed to add `JWT_SECRET` to get it to work)
2. Added a Google Calendar integration
3. Toggled the correct individual calendars on
3. Went to my booking page
4. Confirmed this also is an issue if I use a local deployment (`railway run yarn dev`)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/FNKKX

**Comment by artistro08** [comment]
The reason why there's no availability is because the time uses 24hr time. If you would like to be done at 5PM, you'll need to enter 17:00 for the end time.

**Comment by joshtemple** [comment]
Got it. There's nothing in the availability UI to suggest that the times are in 24h (except for the absence of AM/PM, which is easy to miss). Maybe a toggle or a hint in the description would make that more obvious.

Also, the form should probably validate that 9:00 start and 5:00 end Isn't a valid interval within a 24h day.

**Comment by joshtemple** [comment]
I probably wouldn't have struggled with this as much if #643 was fixed.
