### ISSUE TITLE
Docker installation and "Incorrect password"

### ISSUE THREAD

**Issue by kirillt** [calendso/calendso#82]
Hey, I wanted to give Calendso a shot and deploy it on my server.
I deploy everything with Docker, so I sketched simple Dockerfile.

I initialized DB and **used BCrypt** to encrypt my password.
However, upon login I am reaceiving "Incorrect password" error.

Here is a short screencast to demonstrate the whole process:
[calendso_docker_incorrect_password.zip](https://github.com/calendso/calendso/files/6348965/calendso_docker_incorrect_password.zip)

**Comment by kirillt** [comment]
Here are my `.env`, `Dockerfile` and `Makefile` for quicker verification.
[calendso_docker_incorrect_password_src.zip](https://github.com/calendso/calendso/files/6349002/calendso_docker_incorrect_password_src.zip)

**Comment by baileypumfleet** [comment]
Have you ensured that you've removed the whitespace around the bcrypt hash?

**Comment by kirillt** [comment]
Damn, that's it indeed!

**Comment by s-gbz** [comment]
I've seen the issue in EVERY single calendso setup I've seen so far :smile: 
- https://github.com/calendso/docker/issues/4
-  https://github.com/calendso/docker/issues/5
- https://www.youtube.com/watch?v=BoB0V6Brfdg
- https://www.youtube.com/watch?v=BoB0V6Brfdg (don't remember 100% in this case)
