### ISSUE TITLE
Typeerror at login after updating

### ISSUE THREAD

**Issue by EricDiepeveen** [calendso/calendso#856]
After updating to the latest commit version I am unable to login.

### Technical details

`event - build page: /auth/login
wait  - compiling...
event - compiled successfully
prisma:query SELECT 1
prisma:query SELECT "public"."users"."id", "public"."users"."username", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."password", "public"."users"."bio", "public"."users"."avatar", "public"."users"."timeZone", "public"."users"."weekStart", "public"."users"."startTime", "public"."users"."endTime", "public"."users"."bufferTime", "public"."users"."hideBranding", "public"."users"."theme", "public"."users"."created", "public"."users"."completedOnboarding", "public"."users"."locale", "public"."users"."twoFactorSecret", "public"."users"."twoFactorEnabled", "public"."users"."plan" FROM "public"."users" WHERE "public"."users"."email" = $1 LIMIT $2 OFFSET $3
[next-auth][warn][jwt_auto_generated_signing_key] 
https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
error - unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:333:9)
    at hkdf_extract (/home/ubuntu/calendso/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/home/ubuntu/calendso/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/home/ubuntu/calendso/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/home/ubuntu/calendso/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/home/ubuntu/calendso/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/home/ubuntu/calendso/node_modules/next-auth/dist/server/routes/callback.js:318:37) {
  code: 'ERR_INVALID_ARG_TYPE'
}
wait  - compiling...
event - compiled successfully`

**Comment by emrysal** [comment]
Hi @EricDiepeveen - you need to add a JWT_SECRET to your .env file, e.g. `JWT_SECRET=your_secure_string`

**Comment by EricDiepeveen** [comment]
This resolved my issue. Thanks

**Comment by EricDiepeveen** [comment]
> Hi @EricDiepeveen - you need to add a JWT_SECRET to your .env file, e.g. `JWT_SECRET=your_secure_string`

This resolved my issue. Thanks
