### ISSUE TITLE
user setup

### ISSUE THREAD

**Issue by kylerlaird** [calendso/calendso#86]
I'm new to Calendso.  I'd be happy to work through the documentation but I see that docs.calendso.com is without an address.  I'm guessing that means docs are not yet developed.

I was finally able to get Calendso installed on an Ubuntu instance.  I'm having trouble creating a Calendso user.  When I create one through Prisma Studio, the password that I enter is transformed to "null".  I was hoping it's just getting hidden from display, but when I attempt to log in as that user, I get "Illegal arguments: string, object  An error occurred when logging you in. Head back to the login screen and try again."  I'm guessing that the object is "null" and it needs a password string.

Is there something special about the password field?  Is it plaintext or a specially-formatted hash?

**Comment by kylerlaird** [comment]
I went back to Prisma Studio and changed the password from null on the existing record.  It seems to have saved the non-null value now.  (The first time I did it was when I initially created the row.)

Unfortunately, I am still not able to log in.  Now I get "Incorrect password  An error occurred when logging you in. Head back to the login screen and try again."

I'm hoping I need to put a hash in there.

**Comment by baileypumfleet** [comment]
Yes, you need to add the bcrypt hash to the password field, and ensure there is no extra white space.

**Comment by kylerlaird** [comment]
Thanks!  That did it.

```
$ python3 -c "import bcrypt; print(bcrypt.hashpw(b'my_password', bcrypt.gensalt()))"
b'$2b$12$aWHxn0PEq1MK0quN3j8kH.R68iD8wAW..H1aKpFU4JNaAERyJ3V4W'
```

**Comment by PabloCastellano** [comment]
I had the same issue. I used the [recommended bcrypt generator](https://bcrypt-generator.com/) and could not log in because "Incorrect password".

The one-liner proposed by @kylerlaird worked fine though!
