### ISSUE TITLE
Security Vulnerability on https://app.cal.com/auth/login

### ISSUE THREAD

**Issue by DEV696** [calendso/calendso#891]
I have identified a security vulnerability. Kindly let me know if we can discuss this in detail to keep the product secure. Cheers!

**Comment by baileypumfleet** [comment]
Certainly! Would you be able to join our community Slack (https://cal.com/slack) and DM me, Bailey Pumfleet?

**Comment by DEV696** [comment]
Thanks for giving your time to discuss the vulnerability. We will be waiting for your response on the closure/patch on the vulnerability.
