### ISSUE TITLE
Add a loading state for the book now button

### ISSUE THREAD

**Issue by baileypumfleet** [calendso/calendso#90]
Often when people book an event, because the booking API call isn’t that fast, they press it twice. And if they press the button twice, it books it twice.

Need to add a loading state for when the button has been pressed, so it displays a spinner in the button or something and disables the button while it loads.

**Comment by iamtabrezkhan** [comment]
Hi,
This sounds like a needed enhancement. I can start working on this if no one has already.

**Comment by baileypumfleet** [comment]
done
