### ISSUE TITLE
Is there any way we can have a guide to deploy this on vercel?

### ISSUE THREAD

**Issue by soneji** [calendso/calendso#92]
It would be cool and a lot easier to deploy self hosted if we had instructions for vercel.

Especially I am wondering about how we could deploy to vercel, but also have regular security updates.

I am thinking maybe one (or a combination) of these things could help solve this:
- a template repository
- a GitHub Action to automate updates
- an automated update script
- extraction of "white label" stuff to a .env or other similar file to simplify the update script

**Comment by baileypumfleet** [comment]
Calendso is a Next.js based application, so there are a plethora of resources online that you can use instead detailing how to deploy Next.js apps on any platform.

**Comment by soneji** [comment]
Thanks for the prompt reply @baileypumfleet 

Have you read my full message? Maybe I should open a new issue with the follow up question regarding updates
