### ISSUE TITLE
Automated Updates

### ISSUE THREAD

**Issue by soneji** [calendso/calendso#93]
Is there any way to automate updates for this?

Say for example I was to clone the repo on my server and set it up, I would have to manually SSH into my server, run a `git pull`, fix any merge conflicts, etc. There should be a more elegant way of solving this problem

I am thinking maybe one (or a combination) of these things could help solve this:
  - a template repository
  - a GitHub Action to automate updates
  - an automated update script
  - extraction of "white label" and any other customisable stuff to a .env or other similar file to simplify the update script
  - Docker deployments (while this would allow automated updates for docker users, I still think the app should be easily upgradable for non docker users)
  - a checker for new GitHub releases?

I think an important feature of an automated updater would be to remove git from the equation, although this might not be possible.

**Comment by emrysal** [comment]
@baileypumfleet's intention is that when the application is thoroughly stable; to start tagging releases with full update logs. Currently Calendso can be considered to be running in 'open alpha/beta/preview' mode.  As a sidenote: `git pull` without local changes should never result in a merge conflict; therefore if you want to automatically keep up with HEAD is to do git pull, yarn install (this should also run prisma to update your database), and restart Calendso for good measure.

**Comment by klaytonfaria** [comment]
@soneji May you can fork the repo and then deploy on Vercel with env vars. It should work for you, and you don't need ssh nor a dedicated server to run.
