### ISSUE TITLE
Add a hamburger menu and center all the content on mobile screens  

### ISSUE THREAD

**Issue by morelmiles** [calendso/calendso#98]
The content is not centered on mobile screens. Attached is a screenshot of a 320px by 681px mobile screen. Can I go ahead?

![calendso com_](https://user-images.githubusercontent.com/48476293/115827881-9a01a680-a415-11eb-8b3c-a3dc033b238b.png)

**Comment by baileypumfleet** [comment]
Thanks for reporting this. However, the website is a separate, closed source project, so please report all bugs to support@calendso.com

**Comment by PeerRich** [comment]
hey @morelmiles I fixed both for you :)
